### ISSUE TITLE
ext.ServiceName tag not marking spans as "Service Entry Spans"

### ISSUE THREAD

**Issue by ryanschneider** [DataDog/dd-trace-go#1003]
We recently updated a project from from dd-trace-go v1.29.2 to v1.33.0 and noticed this change in behavior.

Previously, we could use `span.SetTag(ext.ServiceName, "foo")` to give a span a new service name, and this would result in both the spans having a different color in the APM flame graph *and* a new `foo` service would show up in our list of APM services.

With 1.33.0, this only works if we pass `tracer.ServiceName("foo")` to `tracer.StartSpan`.  If we use `SetTag` the span ends up with a different color in the APM flame graph, but a new `foo` service is no longer populated.

Looking at the "Traces" view in DataDog APM, with the new package the spans no longer show up when "Service Entry Spans" is selected.

![image](https://user-images.githubusercontent.com/53520/132598320-22d57431-44c1-42b3-bde9-f7351b4a76f1.png)

If this change is intended, it might be valueable to have `span.SetTag` emit a `log.Warn` message if `ext.ServiceName` is passed in.

**Comment by knusbaum** [comment]
Hi, @ryanschneider.

I'll take a look at this and get back to you.

**Comment by knusbaum** [comment]
@ryanschneider, I am not able to reproduce this.
With `gopkg.in/DataDog/dd-trace-go.v1 v1.33.0` and the following code:
```
package main

import (
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func main() {
	tracer.Start(
		tracer.WithEnv("kn.test.env"),
		tracer.WithService("test-service"),
		tracer.WithServiceVersion("1.2.3"),
	)

	defer tracer.Stop()

	span := tracer.StartSpan("span1")
	defer span.Finish()

	span2 := tracer.StartSpan("span2")
	span2.SetTag(ext.ServiceName, "test-service-2")
	defer span2.Finish()
}
```
I still see the spans in the `Service Entry Spans` list:
![Screen Shot 2021-09-16 at 12 40 47 AM](https://user-images.githubusercontent.com/1819836/133556312-9eae8edd-be72-4c71-b893-ea70db36e55e.png)


When the other span is a child of the first span, I *do not* see both spans listed in the `Service Entry Spans` list:
```
package main

import (
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func main() {
	tracer.Start(
		tracer.WithEnv("kn.test.env4"),
		tracer.WithService("test-service"),
		tracer.WithServiceVersion("1.2.3"),
	)

	defer tracer.Stop()

	span := tracer.StartSpan("span1")
	defer span.Finish()

	span2 := tracer.StartSpan("span2", tracer.ChildOf(span.Context()))
	span2.SetTag(ext.ServiceName, "test-service-2")
	defer span2.Finish()
}
```
![Screen Shot 2021-09-16 at 12 48 30 AM](https://user-images.githubusercontent.com/1819836/133556729-659b67e4-f3e3-4474-8a5d-fd12d5e8a0be.png)

However, I see this same behavior with both the `v1.33.0` and the `v1.29.2` tracer.

There is no behavior that has changed between these tracer versions that should affect this, so I would encourage you to reach out to our support in order to address your issue.

**Comment by darccio** [comment]
Closed due to inactivity.
