### ISSUE TITLE
Update sketches-go to latest version to resolve swag init issues

### ISSUE THREAD

**Issue by kyrozetera** [DataDog/dd-trace-go#1021]
When running `swag init` on our projects, we are seeing this error
```
ParseComment error in file /home/kyro/go/pkg/mod/github.com/!data!dog/sketches-go@v1.0.0/ddsketch/mapping/bit_operation_helper.go :missing required param comment parameters "exponent should be >= -1022 and <= 1023"
```

This was fixed in master of sketches-go, but it hasn't been tagged yet so that this lib can be updated to use the latest version. Is there anything blocking that update?

A reference to the issue can be found here: https://github.com/swaggo/swag/issues/948

**Comment by knusbaum** [comment]
@kyrozetera would you be able to point me to the issue or commit where this issue is fixed in `sketches-go`? 
I see a release published for `DataDog/sketches-go` on September 30 (`v1.2.1`) which should be available now, but want to confirm it actually contains the fix.

We can bump our version in go.mod once there's been a release with the fix in `sketches-go`.

**Comment by kyrozetera** [comment]
It's this commit: https://github.com/DataDog/sketches-go/commit/df181ec336794b1cec5ebe19efb6e7e71204d4ba#diff-56bb1622041d2159ac1379da2bc2fd60ca75ff2bcc0367da33815bed651c974f

It does look like that made it into v1.2.1
