### ISSUE TITLE
github.com/golang/protobuf/proto was deprecated 

### ISSUE THREAD

**Issue by ebilling** [DataDog/dd-trace-go#1136]
The library github.com/golang/protobuf/proto was deprecated over a year ago.

The new home is google.golang.org/protobuf/proto

Also, "github.com/golang/protobuf/jsonpb" has been deprecated by "google.golang.org/protobuf/encoding/protojson"

I have updated quite a few repos recently and I'll try to get a PR to you soon.

**Comment by kaitlinr** [comment]
I'd just like to bump this issue!  We're seeing some security vulns from this package related to `golang.org/x/crypto` and `golang.org/x/text`.

I think this would also involve updating DataDog/sketches-go to 1.3.0.  This means https://github.com/DataDog/dd-trace-go/pull/1051 would need to be merged first.

![image](https://user-images.githubusercontent.com/1081474/155394965-cc3662a6-6377-4523-a0a3-fff160c24ae5.png)

**Comment by dianashevchenko** [comment]
#1051 is now merged, we'll bump protobuf in a moment 🙌

**Comment by radykal-com** [comment]
Any update on this? the deprecated protobuf module is still in go.mod

**Comment by katiehockman** [comment]
We use `govulncheck` as the source of truth for possible vulnerabilities in our code. So that means that our go.mod file could require a version that has a vulnerability in a part of the codebase which isn't reachable from our code. We do this to avoid requiring a higher version in our go.mod file than what is required for users to rely on our code in a secure way.

https://github.com/DataDog/dd-trace-go/blob/main/SECURITY.md#reporting-a-vulnerability

However, if the tool has missed any vulnerabilities that you feel could affect customers, please file a support ticket so we can address that quickly.

**Comment by katiehockman** [comment]
As far as the use of deprecated packages though, that's completely fine to fix. We can address that shortly.

**Comment by zarirhamza** [comment]
Just jumping in real quick - We’re looking into right now and it seems that since we support an older version of one of the grpc libraries, we’re unable to remove the dependency right away without looking into some alternatives. Rest assured we are looking into it and will continue to keep you updated.

**Comment by Teko012** [comment]
@piochelepiotr It seems like after https://github.com/DataDog/dd-trace-go/pull/2694, it is still requred. Do you know what causes this, and can it be solved?

**Comment by darccio** [comment]
@Teko012 As we import dependencies for our contribs, some of them still use it. Specifically, `k8s.io/client-go` uses `github.com/golang/protobuf` on purpose. We'll remove or update other dependencies, like [richardartoul/molecule](https://github.com/richardartoul/molecule/pull/21) but we'll have to wait for Kubernetes to remove it. They have [an issue](https://github.com/kubernetes/kubernetes/issues/96564) where they track their effort to move away from it too.

We are also working on dd-trace-go v2, that isolates contribs as nested modules, so reducing the impact of this kind of dependencies that are deprecated and, sometimes, go stale in other repositories.

Keep in mind that you are not affected unless you import a package that pulls directly the deprecated library or another one that pulls it.
