### ISSUE TITLE
Proposal: Update confluent-kafka-go to v1.8.2

### ISSUE THREAD

**Issue by bigkraig** [DataDog/dd-trace-go#1276]
Current v1.4.0 is a couple of years old.

**Comment by knusbaum** [comment]
Hi, @bigkraig. 

We want to keep the version in our go.mod as low as possible so that the integration remains compatible with older versions. 

This will not prevent you from using the integration with the latest version of confluent-kafka-go. If you put v1.8.2 into your project's go.mod file, dd-trace-go should work fine with it.

If there are any incompatibilities, we can release a new version of the integration compatible with the newer release of the library.
