### ISSUE TITLE
bump github.com/go-kit/kit v0.10.0 to v0.12.0

### ISSUE THREAD

**Issue by nburuzul** [DataDog/dd-trace-go#1303]
github.com/go-kit/kit v0.10.0 internally uses older version of jwt library [github.com/dgrijalva/jwt-go@v3.2.0+incompatible].
github.com/go-kit/kit v0.12.0 is upgraded to use community jwt library [github.com/golang-jwt/jwt v3.2.1]

problem with dgrijalva/jwt-go:
dgrijalva/jwt-go allows attackers to bypass intended access restrictions in situations with []string{} for m["aud"] (which is allowed by the specification). Because the type assertion fails, "" is the value of aud. This is a security problem if the JWT token is presented to a service that lacks its own audience check. There is no patch available and users of jwt-go are advised to migrate to [golang-jwt](https://github.com/golang-jwt/jwt) at version 3.2.1

**Comment by nsrip-dd** [comment]
Hello, thanks for opening this issue. As far as I can tell we don't have any dependency on `github.com/go-kit/kit`:

```
$ go mod graph | grep 'go-kit'
github.com/jackc/pgx/v4@v4.14.0 github.com/go-kit/log@v0.1.0
github.com/go-kit/log@v0.1.0 github.com/go-logfmt/logfmt@v0.5.0
github.com/go-kit/log@v0.1.0 github.com/go-stack/stack@v1.8.0
github.com/jackc/pgx/v4@v4.12.1-0.20210724153913-640aa07df17c github.com/go-kit/log@v0.1.0
```

We do, however, have indirect dependency on `github.com/dgrijalva/jwt-go@v3.2.0`:

```
$ go mod graph | grep jwt
github.com/labstack/echo/v4@v4.2.0 github.com/dgrijalva/jwt-go@v3.2.0+incompatible
github.com/Azure/go-autorest/autorest/adal@v0.5.0 github.com/dgrijalva/jwt-go@v3.2.0+incompatible
```

For the two packages listed here, it looks like `labstack/echo/v4` changed that dependency in version `v4.5.0`: https://github.com/labstack/echo/releases/tag/v4.5.0. Those release notes state that the JWT change is considered breaking. Because of that, I'm not sure if we can upgrade our dependency in this library as it could introduce a breaking change for programs that use this library. However, I believe a downstream user could use `dd-trace-go` with a newer version of the `labstack/echo/v4` package.

As for the Azure package, we get that dependency through `k8s.io/client-go`. That module isn't on a stable version so I'm also not sure we can safely upgrade our dependency without breaking downstream users.

**Comment by nburuzul** [comment]
I am sorry, entered the defect in wrong place. closing it.
