### ISSUE TITLE
question: Increased APM logging when upgrading to 1.38.1

### ISSUE THREAD

**Issue by Gipphe** [DataDog/dd-trace-go#1312]
We have an [echo v4 server](https://github.com/labstack/echo) using the `DataDog/dd-trace-go.v1/ddtrace/tracer` and `DataDog/dd-trace-go.v1/contrib/labstack/echo.v4` packages for APM monitoring on Datadog. We upgraded `gopkg.in/DataDog/dd-trace-go.v1` from `v1.35.0` to `v1.38.1`, and in doing so we saw an immediate uptick in the number of hits to our service

![2022-05-27 19_07_16-Window](https://user-images.githubusercontent.com/2266817/170943580-e8daa941-bc4c-4f12-97dc-b2599b0cda77.png)
 
We promptly reverted the upgrade, and investigated the issue. Looking through the actual logs, there does not seem to be an actual increase in traffic, and can only conclude that the sampling rate has changed. This issue was not discovered in testing, as the traffic volume in our test environment is not large enough to trigger the sampling regardless.

Looking through [the release notes for each release since `v1.35.0`](https://github.com/DataDog/dd-trace-go/releases), there are no clear changes that would cause this sort of logging behaviour, as far as we can tell.

What specific changes since `v1.35.0` would cause this increase in logging? And is there a way to retain the same sampling rate in `v1.38.1` and later?

**Comment by ajgajg1134** [comment]
Hello!
I took a look at the release notes since v1.35.0 and the only thing that jumps out to me is this regression fix in v1.36.0 https://github.com/DataDog/dd-trace-go/pull/1139. Do your trace stats align with the expected traffic you're seeing? Perhaps the sampling rate didn't change, but the hits metrics in version v1.35.0 was wrong due to the tracer dropping some spans before they got to the agent?

It's difficult to tell for certain what exactly could be happen. I recommend opening a support ticket directly with Datadog so they can gather information like Agent version, and you can provide access to support to these metrics / traces, making it much easier to debug.

Thanks!
