### ISSUE TITLE
proposal: contrib/internal/httptrace: refactor span start options handling

### ISSUE THREAD

**Issue by Hellzy** [DataDog/dd-trace-go#1352]
Options can be added to an existing slice of options either by either append'ing at the front or the back of the slice.
The current behaviour is that appending at the back will overwrite any similar option already present, while at the front
the option will get overwritten by any option already present.

TODO: refactor the way span start options are appended, discuss/normalise/rethink the "back/front" convention for span start options.

- Discussion: https://github.com/DataDog/dd-trace-go/pull/1346#discussion_r902893363
- https://github.com/DataDog/dd-trace-go/pull/1346

**Comment by katiehockman** [comment]
@Hellzy is this still something that you feel we should pursue? Not sure what we can do here other than document this better. I'd certainly be concerned with changing the default behavior now since some customers may depend on the conventions we have right now.

**Comment by ajgajg1134** [comment]
Do we know of anywhere in the public contrib packages where this is an issue today? From discussion in proposal meeting it seems like we'd be OK to choose and document a consistent approach for internal/httptrace (probably where the caller is allowed to overwrite via the options). Especially since this is an internal shared package. (So consider this tentatively-accepted?)

**Comment by katiehockman** [comment]
Since it's been a year since this was opened, and there's been little to no traction, I'll close this issue for now. Please re-open if you still think we should pursue this!

**Comment by katiehockman** [comment]
Given https://github.com/DataDog/dd-trace-go/pull/2418, let's re-open this.
