### ISSUE TITLE
Nested span leak?

### ISSUE THREAD

**Issue by C-Pro** [DataDog/dd-trace-go#1390]
I have a long lived parent span, and produce many short lived spans from its context using `StartSpanFromContext`.
Looks like span objects are leaking despite i call `span.Finish()` for children spans as fast as I create new ones.

This code leaks memory fast: https://github.com/C-Pro/datadog-spans-test/blob/master/app/app.go

Output looks like this:
```
Alloc = 13 MiB  TotalAlloc = 18 MiB     Sys = 25 MiB    NumGC = 4       HeapObjects = 93933
Alloc = 24 MiB  TotalAlloc = 31 MiB     Sys = 33 MiB    NumGC = 5       HeapObjects = 204058
Alloc = 31 MiB  TotalAlloc = 45 MiB     Sys = 45 MiB    NumGC = 6       HeapObjects = 268657
Alloc = 45 MiB  TotalAlloc = 58 MiB     Sys = 54 MiB    NumGC = 6       HeapObjects = 431800
Alloc = 51 MiB  TotalAlloc = 72 MiB     Sys = 62 MiB    NumGC = 7       HeapObjects = 472666
Alloc = 65 MiB  TotalAlloc = 85 MiB     Sys = 76 MiB    NumGC = 7       HeapObjects = 634577
Alloc = 78 MiB  TotalAlloc = 99 MiB     Sys = 93 MiB    NumGC = 7       HeapObjects = 797562
Alloc = 78 MiB  TotalAlloc = 112 MiB    Sys = 93 MiB    NumGC = 8       HeapObjects = 730650
Alloc = 91 MiB  TotalAlloc = 125 MiB    Sys = 105 MiB   NumGC = 8       HeapObjects = 891555
```

I expect child spans to be free for GC collection (no references) after `span.Finish()` call despite parent span still active, or have a documented way to free them.

**Comment by dianashevchenko** [comment]
Parent span holds references to child spans until all of the child spans are finished. Attached code showcases a parent span with continuously increasing number of child spans. I'd advise to avoid a parent span that lives indefinitely. Since parent span isn't modified, it might prove useful to instead add tracer options on spans and separate their creations, so that finished traces are flushed frequently.

**Comment by C-Pro** [comment]
I believe that should be at least mentioned in the docs. I can make a PR.
