### ISSUE TITLE
mocktracer: v1.41.0 breaks mocktracer and user attribute information

### ISSUE THREAD

**Issue by alexdulin** [DataDog/dd-trace-go#1451]
The changes in v1.41.0 break user monitoring with the `mocktracer`, as the properties are now on the span's `Meta` field and not tags. Take the following code example:

```go
package main

import (
	"fmt"

	"github.com/google/uuid"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/mocktracer"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func main() {
	mt := mocktracer.Start()
	defer mt.Stop()

	userID, sessionID := uuid.New(), uuid.New()
	span := tracer.StartSpan("test")

	tracer.SetUser(span, userID.String(), tracer.WithUserSessionID(sessionID.String()))
	span.Finish()

	for _, sp := range mt.FinishedSpans() {
		fmt.Println(sp)
	}
}
```

With dd-trace-go v1.40.1, that code outputs:
```
name: test
tags: map[string]interface {}{"resource.name":"test", "usr.id":"f07aa37f-dba2-4ccb-ac86-a3a60e930a60", "usr.session_id":"9fb69703-a64f-4c3a-8333-c89baa1b6329"}
start: 2022-08-29 18:36:23.216229832 -0400 EDT m=+0.000598798
finish: 2022-08-29 18:36:23.216231405 -0400 EDT m=+0.000600371
id: 124
parent: 0
trace: 124
baggage: map[string]string(nil)
```

And with v1.41.0:

```
name: test
tags: map[string]interface {}{"resource.name":"test"}
start: 2022-08-29 18:36:44.921828119 -0400 EDT m=+0.000671560
finish: 2022-08-29 18:36:44.921829289 -0400 EDT m=+0.000672729
id: 124
parent: 0
trace: 124
baggage: map[string]string(nil)
````

This makes any tests using `mocktracer` related to adding user information break when upgrading to v1.41.0

**Comment by katiehockman** [comment]
@Hellzy it looks like this is due to the changes made in the PR you merged a few weeks ago: https://github.com/DataDog/dd-trace-go/pull/1387/files#diff-ad86e517e9501587fea706a500cf65dbf92b14f3c3bfc3f821194125a3c79d46.
Can you take a look to see what we can do here? Is this an intentional side effect of your PR?
I'm not sure that there's anything we can do in the `mocktracer` explicitly, but LMK if you think of anything.

**Comment by Hellzy** [comment]
Sorry about the delay, taking a look.

**Comment by Julio-Guerra** [comment]
We worked on a solution today with @Hellzy. I will push a PR tomorrow.
In the meantime, feel free to downgrade your dd-trace-go version to v1.40.1 where we didn't do the user id propagation yet that is causing the mocktracer not to see those tags anymore.

**Comment by Hellzy** [comment]
Hi @alexdulin 👋, @Julio-Guerra and I have been discussing a solution for this. Julio will probably be the one taking care of this, we will keep you posted.

@katiehockman we will probably need to make modifications to mocktracer in order to ensure consistency between tracer and mocktracer behaviours regarding user identification.
> Is this an intentional side effect of your PR?

It is not, although this shone a light on the fact that `SetUser()` did not work properly with mocktracer even before the change. The behaviour would be correct for "standalone" spans but erroneous for nested spans, while with the latest tracer version the behaviour is incorrect for both cases. We are aiming to fix that.
