### ISSUE TITLE
proposal: go-redis support redis cluster (NewClusterClient)

### ISSUE THREAD

**Issue by akaiserg** [DataDog/dd-trace-go#1629]
Hi, we are using  go-redis to connect to a redis cluster,  but when I tried to add DD I found that the function doesn't exist :(.  

The Function is __redis.NewClusterClient(&redis.ClusterOptions__

We use this version of  go-redis github.com/go-redis/redis/v8.  Do you have any plans to add this feature? 

Kind regards.

**Comment by vigohe** [comment]
Any plans in supporting it??

**Comment by vyoumans** [comment]
same question.  using go 1.19

**Comment by radykal-com** [comment]
We are using this library to trace redis cluster clients (go-redis v8) with go 1.19. Just create the redis cluster client and use `gopkg.in/DataDog/dd-trace-go.v1/contrib/go-redis/redis.v8.WrapClient` function to add the tracing capabilities to the client.

Example:
```
import (
    goredisv8 "github.com/go-redis/redis/v8"
    redistrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/go-redis/redis.v8"
)

c := goredisv8.NewClusterClient(&redis.ClusterOptions{})
redistrace.WrapClient(c)
```

**Comment by akaiserg** [comment]
Thanks for the info @radykal-com , I just tried it and worked pretty well.  But i'td be great if we saw the redis commands inside the same resource.

**Comment by ajgajg1134** [comment]
Hello 👋 thanks for the suggestion, since there's a large number of different redis `NewClient` types I think we're going to avoid adding a specific `NewClusterClient` method. However it does seem difficult to discover that you can use the `WrapClient` function so we'll add an extra example to make it easier to tell from the documentation how to solve this.

As for your other issue regarding "redis commands inside the same resource" please feel free to either open a separate Github issue or directly open an issue with [Datadog support](https://www.datadoghq.com/support/) :)
