### ISSUE TITLE
Update Gin to latest 1.8.x ?

### ISSUE THREAD

**Issue by denouche** [DataDog/dd-trace-go#1645]
Hello,
I wanted to update Gin in my project dependencies to the latest [1.8.2](https://github.com/gin-gonic/gin/releases/tag/v1.8.2) as this version fix an important vulnerability.
But when I upgrade gin to 1.8.2 I loose the datadog APM, I don't know exactly why.
I wonder if the fact dd-trace-go depends on 1.7.x of Gin, and that Gin context management has been broken in 1.8.x can be the source of my problem.
Is that possible to upgrade the gin dependency of dd-trace-go to 1.8.x please?
Thanks

**Comment by knusbaum** [comment]
> I loose the datadog APM, I don't know exactly why.

Can you provide details on what exactly happens? Does the code fail to compile? Do your traces disappear, etc.

**Comment by arpitparmar5739** [comment]
I am trying to update my dependencies using `go get -u .../.` but getting following error:

`go: github.com/DataDog/go-tuf@v0.5.0: parsing go.mod:
        module declares its path as: github.com/theupdateframework/go-tuf
                but was required as: github.com/DataDog/go-tuf`

It is happening probably because of incompatibility of gin and dd-trace-go. Following are the versions I am using:

gopkg.in/DataDog/dd-trace-go.v1 v1.47.0
github.com/gin-gonic/gin v1.8.1

**Comment by Julio-Guerra** [comment]
If what you want is upgrading gin to >= v1.8.0, then you shouldn't use go get -u like that on every package of dd-trace-go but rather do:

```console
$ go get -u github.com/gin-gonic/gin
$ go mod tidy
```
