### ISSUE TITLE
contrib: support opentracing 

### ISSUE THREAD

**Issue by FlamingTree** [DataDog/dd-trace-go#175]
is there plan?

**Comment by gbbr** [comment]
@FlamingTree we are working on this as we speak. Should be available soon.

**Comment by jontonsoup** [comment]
What is the state of this / the docs? Everything seems outdated. 

I'm having major issues finding examples that show how to properly do anything with open tracing and the "supported" libraries. 

I'd love an example of one clean setup where a full request via gin is traced with sql (gorm) and redis. Does this exist?

**Comment by gbbr** [comment]
Hey @jontonsoup - you can try out our new `v1` tracer. It's under the branch with the same name. It's pretty thoroughly documented in its `godoc` pages. The `opentracer` package should be what you're looking for and should be pretty straightforward. Integrations should just work out of the box. We will be releasing this within the next two weeks.

Let me know how it goes and I'm happy to work with you here if you run into trouble.

**Comment by jontonsoup** [comment]
@gbbr thank you! 

I will try this out and see what happens. 

Will this url be updated in the future so I dont have to pin to a branch?
`gopkg.in/DataDog/dd-trace-go.v1`

**Comment by gbbr** [comment]
The URL will stay `gopkg.in/DataDog/dd-trace-go.v1` and will point to the correct release. Once we release though, we will probably create a tag `v1.0.0` so that it's [semver](https://semver.org) friendly and leave the `v1` branch as a development branch. You're good to go using that URL.

I'm not sure if I understood your question correctly, but once we release new minor releases, we will most likely update that URL too. However, it's always safest that you pin down branch/commit in whatever dependency management solution you are using, be it `dep` or `vgo`.

**Comment by jontonsoup** [comment]
@gbbr 

Any intuition on this? 

Using dep 

```
dep ensure -add gopkg.in/DataDog/dd-trace-go.v1

Solving failure: No versions of gopkg.in/DataDog/dd-trace-go.v1 met constraints:
	v1: Could not introduce gopkg.in/DataDog/dd-trace-go.v1@v1, as its subpackage gopkg.in/DataDog/dd-trace-go.v1 does not contain usable Go code (*build.NoGoError).. (Package is required by (root).)
```

**Comment by jontonsoup** [comment]
okay I lied. Just need to import the sub packages individually. 

```
dep ensure -add gopkg.in/DataDog/dd-trace-go.v1/ddtrace
```

**Comment by gbbr** [comment]
I am going to close this, since our `contrib` folder holds integrations for the Datadog tracer. The integrations for Opentracing are found on the official repository: https://github.com/opentracing-contrib
