### ISSUE TITLE
opentracing and apdex

### ISSUE THREAD

**Issue by pierrre** [DataDog/dd-trace-go#176]
If I use the HTTP integrations, I can enable apdex on the web interface.
However if I build my own spans with Go opentracing, apdex is not displayed.

Which tag is required in the span in order to enable apdex ?
These tags ? https://github.com/DataDog/dd-trace-go/blob/master/opentracing/tags.go

**Comment by palazzem** [comment]
Hello @pierrre ! in order to let our backend identify if that `Span` is a web request (or in general, the apdex must be computed), we need to provide the service metadata info. Actually we provide two different approaches:

* [deprecated, will be removed in newer releases]: you can use our API (so not OpenTracing) to call the `SetServiceInfo`. This is an [example for gin](https://github.com/DataDog/dd-trace-go/blob/master/contrib/gin-gonic/gin/gintrace.go#L20). In that case, what is important is saying that the `service` (the name you provided) for the app `gin-gonic/gin` (it's UI sugar) is of type `ext.AppTypeWeb` (activates apdex for this service and spans)
* [requires Datadog Agent 5.21.1+]: it's enough that your spans (especially root spans) set the `Span.Type` field. In the case of OpenTracing you can just:
```go
span.SetTag("span.type", "web")  // it automatically sets the underlying field
```

Let me know if it helps!

**Comment by pierrre** [comment]
> it's enough that your spans (especially root spans) set the Span.Type field.

That's what I thought. (but I wasn't sure)
I'll check that.

Thanks !

**Comment by palazzem** [comment]
@pierrre you're welcome! let us know if it doesn't work as expected!

**Comment by pierrre** [comment]
I did the second solution
> [requires Datadog Agent 5.21.1+]: it's enough that your spans (especially root spans) set the Span.Type field

I did exactly `span.SetTag("span.type", "web")`
I also updated my agent to `5.21.2`.

But it's not yet working.
Should I wait some time ?

**Comment by palazzem** [comment]
@pierrre let me check from our side what we're receiving. The code you wrote is correct and it should trigger this call https://github.com/DataDog/dd-trace-go/blob/master/opentracing/span.go#L63-L66 (assuming you're using the OpenTracing Tracer).

**Comment by pierrre** [comment]
In my code, i'm calling this function for my root span
```go
span.SetTag(ddtrace_opentracing.SpanType, "web")
```
so I think it is calling https://github.com/DataDog/dd-trace-go/blob/master/opentracing/span.go#L63-L66
BTW, I'm currently using revision `6ba9d7ab13ac75d2b739571566f30e4d3ebe39e9`.

I'm also using the latest Agent:
```
======================
Trace Agent (v 5.21.2)
======================
```

I think that the span type is correctly set, because my span is displayed with an earth/world icon. (previously it was a gears icon)

However, I can still not enable apdex as mentioned here https://help.datadoghq.com/hc/en-us/articles/115003346666-How-to-configure-an-Apdex-for-your-traces-with-Datadog-APM-
It is not available instead of latency.

Should I contact your support instead ?
Or can I give you my account if you want to check (email? organization? project?)

**Comment by palazzem** [comment]
@pierrre yes in that case the library is behaving correctly but maybe there is something else that is missing. Can you give me your organization name? I can help you with that without entering our support pipeline (that anyway is very good and active :) )

**Comment by palazzem** [comment]
@pierrre just to be 100% sure, if you access to your service (where we list your resources/endpoints for the given service) and you click the Latency dropdown, you don't see Apdex? if yes, you may see some values (probably it would be 1.0 for a staging env with low traffic).

**Comment by pierrre** [comment]
> Can you give me your organization name

It is `SendinBlue`, and my login is `pierre@sendinblue.com`.
And the service name is `mongodb-current-op`

> click the Latency dropdown, you don't see Apdex

Actually there is no dropdown at all  !
It used to work for some previous tests (maybe without opentracing)

**Comment by LotharSee** [comment]
Hi @pierrre,

Thanks for the report and all the details!
The issue is now fixed on your account.

For context, the issue was that the type of this service used to be reported with `SetServiceInfo`. As this is a user-reported value we give it precedence over the `span.type` (which is usually automatic from the integrations). As a result, we still had the `monitor` type for this service.
We cleared this value. The system now picked `web` which is the type reported by your `mongodb-current-op` traces.

If you have similar services which used `SetServiceInfo` and that you want to update its type, we suggest your to update it with `SetServiceInfo` (might require an Agent restart). Once updated (or for new services), you can simply rely on the `span.type`.

**Comment by pierrre** [comment]
ok, thank you for your help ! 👍
