### ISSUE TITLE
[BUG] contrib/net/http: unable to add multiple RoundTripperOption to the WrapClient

### ISSUE THREAD

**Issue by exilednick** [DataDog/dd-trace-go#1804]
**Version of dd-trace-go**

1.47.0

**Describe what happened:**

I am trying to add a resource name in an outgoing external http request
I accomplished this using the `RTWithResourceNamer` 

      namer := func(r *http.Request) string {
		      return fmt.Sprintf("ext_%s", resourceName)
	      }

	  opt := httptrace.RTWithResourceNamer(namer)
	  client = httptrace.WrapClient(client, opt)
	  
This works as expected and changes the name of the resource
But when i add an extra option to WrapClient's paramter, it only takes one and ignores the other

      namer := func(r *http.Request) string {
		                return fmt.Sprintf("ext_%s", resourceName)
	                }

	  opt := httptrace.RTWithResourceNamer(namer)	  
	  x := func(x *ddtrace.StartSpanConfig) {
		x.Tags = map[string]interface{}{
			"client": "aa"
		}
	  }
	  opts2 := httptrace.RTWithSpanOptions(x)
  
	  client = httptrace.WrapClient(client, opt, opts2)

This does add the tag but ignores the `opt` and instead takes the default resourceNamer - `http.request`
WrapClient does accept a list of options but is only applying one in this case

**Comment by rarguelloF** [comment]
Hi @exilednick and thanks for opening this issue!

In the example above, you are reassigning the `Tags` from the `*ddtrace.StartSpanConfig` to a new `map[string]interface`, so that's why you see this behavior where all the other tags are disappearing. I think what you want to do in this case is adding a new tag, so you could achieve that by doing:

```go
x := func(x *ddtrace.StartSpanConfig) {
	x.Tags["client"] = "aa"
  }
```

Please let me know if this solves your problem, so we can close this issue 😄
