### ISSUE TITLE
tracer: warning for valid tracestate value

### ISSUE THREAD

**Issue by daisy1754** [DataDog/dd-trace-go#2112]
**Version of dd-trace-go**
Datadog Tracer v1.51.0

**Describe what happened:**
While checking at our log, I noticed we have a quite few of log like this
> 2023/07/14 11:54:27 Datadog Tracer v1.51.0 WARN: Won't propagate tag 'tracestate': value contains an invalid character 44

**Describe what you expected:**
No error message

**Steps to reproduce the issue:**
cannot see this in local or dev, only happens in sandbox and prod

**Additional environment details (Version of Go, Operating System, etc.):**
go 1.19

**Comment by ajgajg1134** [comment]
👋 Hello! Thanks for opening this issue, I took an initial look at this and you're right this log warning shouldn't be appearing. It does appear that the functionality for `tracestate` propagation is still functioning, ie the tag **is** still being propagated this is just an erroneous warning log since a different propagation tool believes that `,` is an invalid character. I'll take a look into why that's happening and see how we can resolve this!

**Comment by katiehockman** [comment]
@daisy1754 thanks for filing this issue. Can you clarify what version of dd-trace-go you're using, and what propagation styles your application is using when you see these warnings? I think I see what we can do to fix this, but I want to verify your configuration to make sure.

It's a little surprising at first glance, because that warning is only emitted when `datadog` trace context is being injected, but you're seeing an error for a W3C header, which might actually be reasonable to drop if `tracecontext` isn't in the propagation settings. The answer might be that you should be using `tracecontext` as your propagation style, instead.
