### ISSUE TITLE
opentracing/dd-tracer: no way to set resource as different than name for a rootspan

### ISSUE THREAD

**Issue by gee-m** [DataDog/dd-trace-go#213]
I'm using opentracing/dd to for tracing throughout my gRPC application and on each new call I start a new span from the global tracer (initialized to be datadog's). However, since I initialize the new span for this call with the method name, say `grpc_Status`, the root span and resource is thus set to that. So now when I go to my dashboard, I can't see the different resources listed, I only see the one resource with the root span name that was luckily chosen.

https://github.com/DataDog/dd-trace-go/blob/master/opentracing/tracer.go#L62
Here the root span name == root span resource name, which doesn't allow me to see all my different 'resources' in the DataDog dashboard, for now the way I've gotten around this is: https://github.com/processout/dd-trace-go/pull/1/files

![2e52b9b5-4087-46c6-a44c-6466f1cef618](https://user-images.githubusercontent.com/3154420/38742937-15fb2260-3f3e-11e8-8f24-7be2caee2578.png)

**Comment by gbbr** [comment]
I have two suggestions here:

1. You could use our own gRPC integration, which will give you this out of the box. Any reason you aren't using that? It _should_ work with OpenTracing too.

2. If you don't want to do the above (or if it doesn't work or you can't), you should probably use the same span name for all your spans, such as `grpc.server`. This is logical because it's the same operation, but on different resources. Then, you specifically set the resource on each span to the correct method name. You can do this by setting the tag with the key named "resource.name" available in our OT package as the constant `opentracing.ResourceName`.

I hope this helps. I think any of the above should fix your problem. Let me know how it goes.

**Comment by gee-m** [comment]
Hey, thanks for your answer.

1. Mostly I don't use it because I'm handling streams as well and want to track them too. (so I would need a `StreamInterceptor` as well as a `UnaryInterceptor`.)
2. Great! This sounds like what I was looking for all along. I'll try it out

**Comment by gbbr** [comment]
1. You can use our `UnaryInterceptor` and create a `StreamInterceptor` for yourself. Or even contribute it to the repository.
2. Perfect!
