### ISSUE TITLE
[Feature Request] JSON format output

### ISSUE THREAD

**Issue by tspearconquest** [DataDog/dd-trace-go#2295]
Hello! I'm a user of Traefik ingress controller and encountered a problem today where a log was output from dd-trace-go in plain text format through Traefik because Traefik uses this library to route traces to the datadog agent in our cluster. This is a problem in our environment because our Traefik logs are in json format. Since Traefik uses this library, and the library is outputting the below error in plain text, it is causing Traefik to output the same in plain text.

```
2023/10/24 22:02:03 Datadog Tracer v1.51.0 ERROR: failure sending traces (attempt 1), will retry: Post "http://datadog.datadog.svc.cluster.local:8126/v0.4/traces": context deadline exceeded (Client.Timeout exceeded while awaiting headers) (occurred: 24 Oct 23 22:01 UTC)
2023/10/24 22:02:03 Datadog Tracer v1.51.0 ERROR: lost 2 traces: <nil> (occurred: 24 Oct 23 22:01 UTC)
```

Normally this wouldn't be an issue, but our traefik logs are picked up by a log parser (fluentd) and expected to be in JSON format. Because these logs are not JSON formatted, it causes a parse error to be logged in our fluentd instance, and these log entries are not forwarded. We would like to be able to forward these errors to our log sink along with our Traefik logs, but because of the parse error, they can't currently be forwarded.

Would it be possible to provide a way to configure either the log message output or configure the output format itself, for downstream projects using this library? If it's already implemented and just needs the downstream project to configure it, please let me know so that I can engage with the Traefik folks to take a look from their side.

**Comment by darccio** [comment]
Hi @tspearconquest, thanks for your request. We already have the issue #2152 tracking this.

As mentioned in [the docs](https://docs.datadoghq.com/tracing/troubleshooting/tracer_startup_logs/), the current output format is an intentional behavior of the tracer, as these prefixes are meant to simplify the search within your logs. They are also unified across the different Datadog tracers.

We're not against giving users and we'll welcome any contribution allowing to configure the output format.

If you don't mind, I'd advise to subscribe to #2152, close this issue and, for better tracking and prioritization, also reach out to the [support team](https://www.datadoghq.com/support/) and submit a feature request. Thanks again!
