### ISSUE TITLE
contrib/net/http: monitoring of client-side errors

### ISSUE THREAD

**Issue by marchelbling** [DataDog/dd-trace-go#244]
We've started using APM to monitor some of our APIs and are pretty pleased.
We just feel like the global view of what our APIs return is missing. For example with have quite a lot of HTTP request validation going on; those would return 4xx and we need to monitor this.

Currently only 5xx are considered errors. A simple approach to allow for monitoring 4xx would be to provide a user option to configure if client errors should also be considered as errors. 

Another option would be to push a status custom metric (from https://github.com/DataDog/dd-trace-go/blob/master/contrib/internal/trace.go) tagged by service. While this is maybe out of the APM scope, the benefit I'd see with this is that it would not be subject to the APM sampling or rate limiting.

**Comment by gbbr** [comment]
> We've started using APM to monitor some of our APIs and are pretty pleased.

Great! We are definitely happy to hear this!

> Currently only 5xx are considered errors. A simple approach to allow for monitoring 4xx would be to provide a user option to configure if client errors should also be considered as errors.

Unfortunately this isn't something that we want to do because this would only be an error from the perspective of a client trace. A server trace should not mark itself as erroneous in these cases as the problem lies on the client side.

> For example with have quite a lot of HTTP request validation going on; those would return 4xx and we need to monitor this. [...] the benefit I'd see with this is that it would not be subject to the APM sampling or rate limiting.

From the above I get that you are trying to work around the agent error sampling. If so, you could avoid this by using sampling priority. In the `v1` tracer you would do this by marking the root span of a trace like this:

```go
span.SetTag(ext.SamplingPriority, <value>)
```

Where `value` can be any of [these values](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/ext/priority.go).

**Comment by gbbr** [comment]
I will close this as I consider the answer sufficient. If there are any other concerns or you feel otherwise, feel free to comment.
