### ISSUE TITLE
pgx query times report as application times in the Datadog UI

### ISSUE THREAD

**Issue by ewhauser** [DataDog/dd-trace-go#2710]
**Version of dd-trace-go**
latest

**Describe what happened:**

We recently switched from `libpq` to `pgx`. Our services are now showing all time spent in the application vs. correctly reporting on the application and database times.

**Describe what you expected:**

The screenshot shows the difference here. The `pgx` changes were deployed on Thurs 23rd and our service name is `telemetry`:

<img width="717" alt="Screenshot 2024-05-25 at 9 07 09 AM" src="https://github.com/DataDog/dd-trace-go/assets/131389/bb30309f-d4fd-44aa-8cb9-3ff255b6f848">

**Steps to reproduce the issue:**
Should be simple to reproduce. Send any `pgx` traces to Datadog.

**Additional environment details (Version of Go, Operating System, etc.):**

**Comment by darccio** [comment]
@rarguelloF @zarirhamza Can you review this? Thanks!

**Comment by rarguelloF** [comment]
@ewhauser Sorry for the delayed response.

From the screenshot you are sending, it seems the `postgres.db` service disappeared, which is something expected as the `pgx.v5` integration by default inherits the service name from `DD_SERVICE` instead of setting a custom one. We are aware this is an inconsistent behavior between different instrumentations, but overall the preferred behavior from now on is to get rid of these "fake" services (like `postgres.db`) and instead using `DD_SERVICE` everywhere in the same service. The `DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED` environment variable ensures this behavior is applied in every integration/instrumentation you are using.

If you want to have the old behavior (having your `pgx.v5` spans with a different service name), you can do the following:

```go

import (
	pgxtrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/jackc/pgx.v5"
)

// ...

db, err := pgxtrace.Connect(ctx, dbUrl, pgxtrace.WithServiceName("postgres.db"))
```

**Comment by darccio** [comment]
Since the question is answered, we close the issue. Feel free to reopen if you want more support.
