### ISSUE TITLE
[BUG] Datadog Tracer v1.64.0 WARN: Turning off Data Streams Monitoring. Upgrade your agent to 7.34+

### ISSUE THREAD

**Issue by promiseofcake** [DataDog/dd-trace-go#2726]
We are seeing an issue that might be the result of a race condition at tracer / host startup. We keep getting these warning messages:

`Datadog Tracer v1.64.0 WARN: Turning off Data Streams Monitoring. Upgrade your agent to 7.34+`

And it's tightly coupled to hosts which have recently come online.

**Version of dd-trace-go**

v1.64.0

**Describe what happened:**

There is a race condition between the tracer library and the Datadog agent being ready on new EKS hosts which causes certain functionality for DSM to be disabled (namely flushing stats).

**Describe what you expected:**

I expect the agent to reply in time, or the library to block while waiting if functionality will be disabled for the entirety of the library execution.

**Steps to reproduce the issue:**

**Additional environment details (Version of Go, Operating System, etc.):**

Go 1.22
EKS 
Datadog Agent via Helm as Daemonset.

**Comment by darccio** [comment]
Thanks @promiseofcake for reporting this. The exact function that is obtaining the agent features can be found [here](https://github.com/DataDog/dd-trace-go/blob/6126fb6b6013a51716a38f43a4b6e3f992f04094/ddtrace/tracer/option.go#L626). It's passed to DSM Processor later [here](https://github.com/DataDog/dd-trace-go/blob/6126fb6b6013a51716a38f43a4b6e3f992f04094/ddtrace/tracer/tracer.go#L266) and called for the first time [here](https://github.com/DataDog/dd-trace-go/blob/6126fb6b6013a51716a38f43a4b6e3f992f04094/internal/datastreams/processor.go#L224).

Do you see any other error messages around the one you reported? The function is completely synchronous, as it issues an HTTP request to the agent to a specific endpoint available from `v7.28.0`. We don't think there is a race condition, at least in the tracer.

I assigned the issue to @piochelepiotr so he can give us more insights as DSM library dev. In any case, I'd suggest to contact support in order to make sure your deployment has the right agent version and the agent is accessible.

**Comment by jungnoh** [comment]
We are experiencing this issue as well. We get the same error message `Datadog Tracer v1.64.0 WARN: Turning off Data Streams Monitoring. Upgrade your agent to 7.34+` when a pod starts on a new host, but the error does not appear after restarting the pod's container.

Our environment is dd-trace-go v1.64.0, Datadog Agent v7.54.1, EKS 1.29.

**Comment by darccio** [comment]
@jungnoh @promiseofcake We've decided to remove the verification in #2756, so we won't disable DSM in the event of not being able to reach the agent.

This will be available in our next release, expected to start at the beginning of July.

**Comment by promiseofcake** [comment]
Hey @darccio do you know when you plan to do the next release?

**Comment by darccio** [comment]
@promiseofcake It's still in progress but close to the end. @dianashevchenko is the release driver.

**Comment by darccio** [comment]
@promiseofcake It's been released as `v1.66.0`.
