### ISSUE TITLE
contrib/google.golang.org/grpc: allow customizing which status codes count as errors

### ISSUE THREAD

**Issue by ewang** [DataDog/dd-trace-go#333]
In the Go gRPC handlers, any non-OK response status are returned via an error. I'd like to be able to treat certain non-OK response status codes as non-errors.

The stream server interceptor treats certain error values as non-errors [1], but I'd like to be able to customize this list further (e.g. don't treat gRPC NotFound and InvalidArgument status codes as non-errors). The unary server interceptor currently just passes the error directly to the tracer WithError function.

One option might be to introduce a new interceptor option that allows passing in a custom function to allow rewriting the error value similar to withStreamError.

Ref:
[1] https://github.com/DataDog/dd-trace-go/blob/v1/contrib/google.golang.org/grpc/grpc.go#L37

**Comment by gbbr** [comment]
We've had similar requests before and have generally ended up that it's valid to have these as errors. Would you be able to provide more detail as to why this is a problem for you?

**Comment by ewang** [comment]
Here are my thoughts:

1) The behavior is currently inconsistent between the stream and unary. For example, in the stream interceptor, codes.Canceled is special cased as non-error while in unary it's an error. That list of special cased errors in the stream interceptor also seems somewhat arbitrary.

2) In the HTTP traces, 3xx and 4xx don't seem to be considered errors (although their status codes are colored orange). Wondering if we could have something similar for gRPC. In particular I'd like for certain error codes to not be counted in the APM Errors chart.

**Comment by gbbr** [comment]
@dd-caleb do you have any thoughts on this? Should we groom these codes some more in the style of HTTP client and server errors? Or would it make sense to introduce another option for the interceptors such as:
```go
grpctrace.StreamClientInterceptor(grpctrace.NonErrorCodes(codes.NotFound, codes.InvalidArgument, ...))
// will not regard codes.NotFound and codes.InvalidArgument as an error
```

**Comment by gbbr** [comment]
@ewang would my suggestion above be a reasonable resolution for you?

**Comment by dd-caleb** [comment]
I think it probably makes sense to treat EOF and Cancelled as non-errors in the unary method too. I would also be in favor of an option to customize this.

As an example, we had a service that implemented backoff via the ResourceExhausted error code and in our case it would've been nice not to report that as an error, since the client handled it in a special way, and it happened quite frequently.

**Comment by gbbr** [comment]
Ok, let's move forward with this new option then, as specified in my previous comment. It should support an arbitrary number of `codes.Code` arguments and store them in a `map[codes.Code]struct{}` for fast access.

We could do this as follow-up work to #334 inside the [suggested](https://github.com/DataDog/dd-trace-go/pull/334#issuecomment-422379005) function `finishWithError`.

**Comment by ewang** [comment]
I think a custom option that accepts codes.Code values is fine. But why is context.Canceled error given special treatment there? That part won't be customizable via the custom option proposed above.

The other more generalized option would be to accept a callback func that allows re-writing the error.

**Comment by gbbr** [comment]
Both are very good questions.

> I think a custom option that accepts codes.Code values is fine. But why is context.Canceled error given special treatment there? That part won't be customizable via the custom option proposed above.

I actually don't know the answer. Let's not give it special treatment and consider it an error. @dd-caleb any objections to this?

> The other more generalized option would be to accept a callback func that allows re-writing the error.

Yes, that would ideally be the ultimate solution. I'd like to avoid this however to try and stop people from adding too much logic in there and potentially slowing down instrumentation. Having the option that takes codes will guarantee good performance since the logic is in our hands.

If we are to ever add a callback that gives errors special treatment, it should be in the tracer itself, not the integration. This is something that we have been considering for a long time now but wasn't really pressing yet.

**Comment by ewang** [comment]
How are we thinking to handle this breaking change in behavior for removing context.Canceled? Just tag a new version and make note of the breaking change?

Also, I believe the latest gRPC specs state that handlers should only return errors via the gRPC status package. So I think that assumption allows us to only have to consider codes.Code; maybe io.EOF shouldn’t have special treatment here either since it should’ve been handled by the handler.

**Comment by gbbr** [comment]
We can now move forward and implement this, since #334 was now merged. The plan is:
* Add `NonErrorCodes(c ...codes.Code)` interceptor option and save these codes in a new field `nonErrorCodes map[codes.Code]struct{}` inside [*interceptorConfig](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/google.golang.org/grpc/option.go#L3).
* Make the default value of it inside the [defaults](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/google.golang.org/grpc/option.go#L26) function `map[codes.Code]struct{}{codes.Canceled: struct{}{}}` so we can keep backwards compatibility.
* Pass the config object as an argument to [`finishWithError`](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/google.golang.org/grpc/grpc.go#L35) and if the status code is found in the map, set the error to `nil`.

@kazegusuri or @ewang let me know if you'd like to commit to this. Otherwise I'll set it up when I get a chance.

**Comment by ewang** [comment]
@gbbr Makes sense to keep io.EOF as a special case for backward compatibility reasons given it doesn't have a corresponding value in codes.Code -- in practice conforming handler implementations shouldn't hit that case anyways. Perhaps a note somewhere to consider cleaning this bit up when there's a future v2 branch release.

The plan sounds solid. I won't be able to commit to it until end of month earliest, so I'll check back then to see if this still needs someone to help implement.

**Comment by lhecker** [comment]
I'm not sure why GitHub didn't link my PR but here it is: https://github.com/DataDog/dd-trace-go/pull/414

**Comment by fantapop** [comment]
> We've had similar requests before and have generally ended up that it's valid to have these as errors. Would you be able to provide more detail as to why this is a problem for you?
Sorry to comment on such an old issue but my comment was related and I'm not sure where else to ask it.  I tend to agree that it's valid to have these as errors but also that having them in the default APM dashboard makes it much less useful.  It would be great if DataDog had first class support for the concept of "end user caused" errors.  The APM dashboard could provide a switch to show them or not. In that way actionable errors would still be easy to see and I could still have monitors that look for anomalous changes to "end user caused" errors.  I assume this isn't isn't really the place to add this feature request. But I'm interested in thoughts on whether others would find this to be a useful feature.
