### ISSUE TITLE
contrib/database/sql: Include paramaters as metadata?

### ISSUE THREAD

**Issue by jimtla** [DataDog/dd-trace-go#350]
When running properly quoted queries, the traced query looks like:
```
INSERT INTO sample_notes ( created_by, created_at, last_modified, content ) VALUES ( ? ) RETURNING *
```

Including the values that were passed foe `?` would be incredibly useful for debugging surprisingly slow queries.

**Comment by gbbr** [comment]
Do you mean this for resource names? If yes, we won't be able to do that due to cardinality issues. We could do it however for the individual queries (when you open up a trace in the application) but I'm not sure if that would still be as helpful to you.

**Comment by jimtla** [comment]
The second is exactly what I'm looking for. The quoted query is perfect for resource names, but once I've identified a specific trace that's behaving in a surprising manner, I'd like to be able to reconstruct the full query that was executed. A more realistic example is a query like:

`SELECT * from sample_notes where created_by = ?`.

If User 3 has an order of magnitude more notes than the next most prolific author, we'll see that this query is slow a small percentage of the time. Without seeing the created_by value in the traces, it will be difficult to understand why those invocations of the query were slow, while others perform well. If I can see that the 5 slowest invocations of this query are all for `created_by = 3`, then the problem is obvious.

**Comment by gbbr** [comment]
Got it.

Before considering adding such features in the agent (I have the feeling most people will be against doing it, since exposing SQL information is almost never what anyone wants), I'd like you to consider if you can perhaps use a parent span to add this metadata, and simply pass it as context to the query that you are running (using `QueryContext`, `ExecContext` or `PrepareContext`), this way, you'll be able to see the metadata in the trace. Would that be a reasonable outcome for you?

**Comment by jimtla** [comment]
We can definitely instrument manually, but I'm curious about your statement that "exposing SQL information is almost never what anyone wants" – what makes you say that?

**Comment by knusbaum** [comment]
@jimtla I'm going to close this issue. If you have more suggestions about this, feel free to reopen it.
