### ISSUE TITLE
ddtrace/opentracer: unable to create FollowsFrom reference

### ISSUE THREAD

**Issue by willyyang** [DataDog/dd-trace-go#376]
is there any plan to add the followsFrom reference? https://github.com/DataDog/dd-trace-go/blob/5a8139286014811d2bccd5ef67ec4844ea0998a7/ddtrace/opentracer/tracer.go#L46

**Comment by gbbr** [comment]
Not at the moment. Let's leave this here to track progress if anything changes.

**Comment by vdatcu** [comment]
Hi guys, any news on this?

**Comment by gbbr** [comment]
No update. We're not currently looking to pursue this. If anything changes, we'll be updating this issue, simply subscribe to it to get notified.

**Comment by shannontan-bolt** [comment]
@gbbr - I'd love to understand why this is not supported. As you already know, I've had to fork dd-trace-go so am also thinking about why this doesn't quite work.

Is it the UI that doesn't support FollowFromRef? Is it the tracer?

**Comment by shannontan-bolt** [comment]
If I'm reading the code (and some issues from the opentracing specification) correctly, FollowsFrom doesn't have a consistent UI/tracer representation. I'd love to add a flag to allow FollowsFrom to just be represented as a child - either in my fork or upstream.

Would love to hear your thoughts on that.

**Comment by gbbr** [comment]
That's an interesting idea. I never thought of that as a solution: using a child instead. I'm not sure what the team would think about this. I'd have to check with the rest of APM integrations to see what other languages do because we want to keep it consistent here and we also don't want to confuse people, but I can understand the problem.

And yes, you are right, there is no support for this in the product (UI).

**Comment by gbbr** [comment]
@shannontan-bolt if you'd like, it's fine to create a PR to have `FollowsFrom` result in a child span.

**Comment by shannontan-bolt** [comment]
See #883

**Comment by gbbr** [comment]
Merged. Should be out soon with v1.30.0!
