### ISSUE TITLE
contrib/go-redis/redis: data race at WithContext function

### ISSUE THREAD

**Issue by subroll** [DataDog/dd-trace-go#387]
i found that this package will raise data race condition if we call WithContext function every time before we call the command function, e.g, Set or Get function.

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"sync"

	goredis "github.com/go-redis/redis"
	"gopkg.in/DataDog/dd-trace-go.v1/contrib/go-redis/redis"
)

func main() {
	closeApp := make(chan struct{})
	redisOpt := &goredis.Options{
		DB:       0,
		Addr:     "localhost:6379",
		Password: "",
	}
	redisClient := redis.NewClient(redisOpt)

	go func() {
		sigint := make(chan os.Signal, 1)
		signal.Notify(sigint, os.Interrupt)
		<-sigint

		if err := redisClient.Close(); err != nil {
			log.Fatal(fmt.Sprintf("error when closing redis client. err: %+v\n", err))
		}
		closeApp <- struct{}{}
	}()

	var wg sync.WaitGroup
	wg.Add(2000)
	for i := 1; i <= 2000; i++ {
		go writeData(&wg, redisClient, i)
	}
	wg.Wait()

	for i := 1; i <= 2000; i++ {
		go fetchData(redisClient, i)
	}

	<-closeApp
	close(closeApp)
}

func writeData(wg *sync.WaitGroup, redisClient *redis.Client, iterationNum int) {
	defer wg.Done()

	key := fmt.Sprintf("test_key:%d", iterationNum)
	val, err := redisClient.WithContext(context.Background()).Set(key, iterationNum, 0).Result()
	if err != nil {
		log.Printf("[write] error while writing data. iteration: %d. err: %+v\n", iterationNum, err)
		return
	}

	log.Printf("[write] iteration: %d. \nkey written: %s\n value written: %d\n value returned: %s\n",
		iterationNum, key, iterationNum, val)
}

func fetchData(redisClient *redis.Client, iterationNum int) {
	key := fmt.Sprintf("test_key:%d", iterationNum)
	val, err := redisClient.WithContext(context.Background()).Get(key).Result()
	if err != nil {
		log.Printf("[read] error while fetching data. iteration: %d. err: %+v\n", iterationNum, err)
		return
	}

	log.Printf("[read] iteration: %d\n key read: %s\n value read: %s", iterationNum, key, val)
}
```

**Comment by gbbr** [comment]
@wisnuseptiaji you're right. There is a race condition here. Thanks for reporting it.

**Comment by cranti** [comment]
Can this issue be reopened? https://github.com/DataDog/dd-trace-go/pull/390 indicated that it would be

**Comment by knusbaum** [comment]
It looks like #390 was closed and not merged. Should it have been?
Either way, the original code that fixes this bug is still in place: https://github.com/DataDog/dd-trace-go/blob/a5bb23ba163c79527ac882082eacc4bd96453d4e/contrib/go-redis/redis/redis.go#L27-L33

**Comment by gbbr** [comment]
#388 only slightly improves the problem, but still leaves a race condition present. Given the two commands:
```
client.WithContext(ctx1).Append("k1", "v1")
client.WithContext(ctx2).Append("k2", "v2")
```
There is a race condition between the first and second command because they both override the same context in the same client instance.

The correct implementation would return a copy of the client, but that is a bit more tricky and also has performance considerations. At the time I investigated this, I couldn't find a good way to address the problem. Perhaps another pair of eyes or new commits to the upstream package would change this.

We've not fully reverted this change because we've accepted this compromise of having a working context at the cost of this potential race condition.
