### ISSUE TITLE
proposal: implement binary propagator

### ISSUE THREAD

**Issue by k1ng440** [DataDog/dd-trace-go#406]
https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/option.go#L70

WithPropagator() feels useless because some of the important methods are private.

This struct should be public for returning spanContext from a custom Propagator
`type spanContext struct`

following methods should be public because of custom propagator
`spanContext.setSamplingPriority()`
`spanContext.samplingPriority()`
`spanContext.hasSamplingPriority()`
`spanContext.setBaggageItem()`

**Comment by gbbr** [comment]
Is there something you are trying to achieve that you aren't able to?

**Comment by k1ng440** [comment]
Yes. i am trying to create binary propagator myself but its seems its require those 2 methods

```
spanContext.samplingPriority()
spanContext.hasSamplingPriority()
```

**Comment by gbbr** [comment]
It is true that it's not of much help to implement your own propagator at this point because of the issues you've mentioned. Unfortunately we can't change that without breaking the current API, but it's definitely something to consider for 2.0!

In the meantime, do you think you could work with implementing your own [`TextMapReader`](https://github.com/DataDog/dd-trace-go/blob/77612d80c01ab7018947a72bd9077e4b8d055ff9/ddtrace/tracer/propagator.go#L27-L35) and [`TextMapWriter`](https://github.com/DataDog/dd-trace-go/blob/77612d80c01ab7018947a72bd9077e4b8d055ff9/ddtrace/tracer/propagator.go#L19-L25) instead? You could use any encoding you wanted under the hood.

**Comment by k1ng440** [comment]
Actually i have successfully implemented the binary propagator without making any breaking changes. you could leave the WithPropagator() to the user since TextMapReader and TextMapWriter are default. 

i will make a pull request in a moment

**Comment by gbbr** [comment]
Thanks! That's definitely possible to do, without changing the propagator. The PR is welcome.

**Comment by gbbr** [comment]
It's still unclear to me _exactly_ what you are trying to achieve. Can you explain in a few sentences? I'm sure it's been done before.

**Comment by k1ng440** [comment]
all i am trying to do is avoid race condition in our applications.

**Comment by gbbr** [comment]
I'll try and take another look at your code when I get a chance, perhaps I can figure out what you're trying to do. It's still a bit unclear to me.

**Comment by k1ng440** [comment]
it seems my issue was really simple. simply copying the map solved the race problem. sorry for your trouble. 

md = metadata.Copy(md)

**Comment by gbbr** [comment]
No problem! Let’s close this issue and the PR then. What do you think?

**Comment by k1ng440** [comment]
sure
