### ISSUE TITLE
Make logging configurable for tracer

### ISSUE THREAD

**Issue by rkuska** [DataDog/dd-trace-go#432]
We use structured logging (json struct) in our app but dd-trace-go sometimes logs errors as plain text. It would be nice to have an interface and enable passing logger as an option to tracer.

Example of logged messages:
```
  | 2019/04/24 11:18:02 Datadog Tracer Error (v1.10.0): lost traces (count: 10), error: Post http://172.17.0.1:8126/v0.4/traces: dial tcp 172.17.0.1:8126: connect: connection refused
-- | --```

**Comment by gbbr** [comment]
Makes sense. We definitely need this and you're not the only one who's asked for it. I need some time to think this through because if we add a new public interface it'll be permanent and any potential changes in the future might become breaking. There is some work planned for introducing logging levels into our tracing clients, but not in the near term as far as I know.

**Comment by rkuska** [comment]
I would vote for making the interface simple. Use one method for meaningful logs and one for debugging logs (development friendly). User will just provide implementation where he implements the classic function for logging and makes no-op from the one for debugging. Datadog can provide two default loggers, one with no-op debug function and other one where debug log function is implemented.

I believe that 3rd party modules shouldn't log or log only minimally, hence no need for anything complex.

**Comment by gbbr** [comment]
How would you feel about having a callback instead? Something like:
```go
func WithOnError(onError func(msg string)) StartOption
```
I'm not sure if this is a good solution, but maybe it would be safer because it might be easier to potentially deprecate this in favor of an implementation similar to your proposal in the future, when we unify logging throughout our integrations. If we were to add a new interface now and deprecate it later, that would make the API a bit messy.

Would this be equally easy for you to use? It's default value would then be `log.Println`

**Comment by rkuska** [comment]
Sorry, I got sidetracked :-)

I believe that `WithOnError` sounds like a good enough workaround for a time being. Do you want me to contribute with PR (adjust the existing PR)?

**Comment by gbbr** [comment]
Whatever's easier for you is fine by me.

**Comment by gbbr** [comment]
As part of #442 the proposal is:
```go
tracer.Start(tracer.WithLogger(l))
```
Where `l` must implement `ddtrace.Logger` defined as:
```go
type Logger interface {
    Log(msg string)
}
```
I hope that should do it. Still open to proposals while the PR is in review (and even after, until it gets released).

**Comment by rafi-fisker** [comment]
Could we make this logger configurable via env var?

Something like `DD_TRACE_LOG_LEVEL` ?

We are struggling with tracer log spam -
See https://github.com/DataDog/dd-trace-go/issues/945

We have never been able to work around these logs 
![image](https://user-images.githubusercontent.com/72412693/174125253-c82af8ff-ddd5-4ae0-8b36-bde1bebaa87b.png)
