### ISSUE TITLE
contrib/database/sql: No way to set span tag dynamically

### ISSUE THREAD

**Issue by Code-Hex** [DataDog/dd-trace-go#485]
It don't have way to set span tag dynamically. 
we want to know what queries are issued for each endpoint. so want to set endpoint to the span tag.

https://github.com/DataDog/dd-trace-go/blob/a59475992ec658c954de1e89fff55b4bfef54570/contrib/database/sql/conn.go#L136-L163

**Comment by Code-Hex** [comment]
Temporary PR https://github.com/DataDog/dd-trace-go/pull/484 :bow:

**Comment by cgilmour** [comment]
Hi @Code-Hex thanks for opening the issue that was requested.

I have looked at the PR for the initial implementation and would suggest a different approach.

Instead of exposing a context key, I think a function returning the modified context would be better.
Exposing keys directly makes it harder to change things in the future. If we need to change the name or behavior in the future, it would break existing code.

So I would suggest a `With` function to return a modified `context.Context` to add the values to the keys and not exporting the underlying key.
Eg: `WithSpanTags(ctx context.Context, tags map[string]string) context.Context`

Also generally for `context.Context`, the keys need to have a unique and unexported type, to prevent collisions from different packages.
From https://blog.golang.org/context
```go
// The key type is unexported to prevent collisions with context keys defined in
// other packages.
type key int
...
const userIPKey key = 0
```

In this case, I'd be ok with something like
```go
type contextKey int
...
const spanTagsKey key = 0
```
 And that key used in the body of `WithSpanTags`

**Comment by Code-Hex** [comment]
Do you means like this code?

```go
const spanTagContextKey = struct{}{}

func WithSpanTags(ctx context.Context, tags map[string]string) context.Context {
    return context.WithValue(ctx, spanTagContextKey, tags)
}
```

**Comment by cgilmour** [comment]
The problem with `struct{}{}` is that it's comparable even if a different package had that key.
This is solved by having a unique _type_ in addition to the value.
Making that type _unexported_ means no other package can conflict with it too.

So the suggestion is to use:
```
type contextKey int
const spanTagsKey contextKey = 0 // map[string]string
```

And then exactly what you'd written, using `context.WithValue`

**Comment by Code-Hex** [comment]
I understand perfectly.
I will fix to that. thanks best suggestion :smile:

**Comment by Code-Hex** [comment]
I've fixed code at https://github.com/DataDog/dd-trace-go/pull/484/commits/f96cff4fee1512e8e484d67047869b6ceacfb29a
Review please :bow:
