### ISSUE TITLE
contrib/gorilla/mux: Cannot disable stack traces on errors

### ISSUE THREAD

**Issue by ashanbrown** [DataDog/dd-trace-go#615]
The gorilla mux integration has some options to add options at span start but not span at finish, which I believe is necessary to disable stack traces.  We use another tool to handle errors, and we have some concern about the potential volume of such stack traces, so we'd prefer not to record a stack traces on each error.

**Comment by gbbr** [comment]
Sounds reasonable. We should maybe be able to do this at a global level and not just per-integration level. Or are you interested only for `gorilla/mux` ?

**Comment by gbbr** [comment]
Have you tried using the `tracer.NoDebugStack` start option? e.g.

```
tracer.Start(tracer.NoDebugStack(), ...)
```

**Comment by ashanbrown** [comment]
From what I can tell at https://github.com/DataDog/dd-trace-go/blob/abcb2fe245d617d32ce39d436f073ec6d13f428d/ddtrace/tracer/option.go#L397  `tracer.NoDebugStack` is a `FinishOption` not a `StartOption` (also it doesn't compile for me).  I could see the case for perhaps adding a `WithFinishOptions` start option but I'm not sure that would make sense in all cases.

**Comment by gbbr** [comment]
Ah, yes, you're right. Sorry about that. My bad. Allow me some time to think about the best solution for this and I'll come back to you. Something similar to your PR could be the way to go, but I'd also like to consider having a global option for this. Would that resolve your problem? The answer would be 'no' only if you'd like to receive no stacks for this integrations and stacks for everything else.

**Comment by gbbr** [comment]
Thanks for your patience. It looks like we already have this (otherwise repetitive) process in most of our integrations. So I'm fine with adding it here too, as long as we stay consistent. Can you please use the same style as elsewhere? This means that the option will be called `NoDebugStack` like for example in our gRPC integration [here](https://github.com/DataDog/dd-trace-go/blob/876b6b3508944c24f204f96d93474b3ec5dd72c6/contrib/google.golang.org/grpc/option.go#L79-L85).
