### ISSUE TITLE
proposal: expose tracer Service, Env and Version.

### ISSUE THREAD

**Issue by knusbaum** [DataDog/dd-trace-go#637]
This is related to the env and service changes made in #529 and #607.

Just like `dd.span_id` and `dd.trace_id`, we want to expose the application version and env for printing in logs:
https://docs.datadoghq.com/tracing/connect_logs_and_traces/go#further-reading

The simplest way to implement this is just by exposing a `func Env() string` and `func Version() string` in the `ddtrace/tracer` package, but I'm not sure that's the best idea. Although spans are almost always going to contain the Version and Env set in the tracer, it's technically possible to set a custom version and/or env for a span. 

A more complete solution would be to expose `Version()` and `Env()` methods in the [`Span interface`](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace#Span), but that's such a clean interface, it seems like a shame to pollute it with these odd functions.

[`SpanContext`](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace#SpanContext) feels like a more natural home for these methods, but the [`spanContext`](https://github.com/DataDog/dd-trace-go/blob/83ba1eba95df40b6f34a7d625cc1b1824257a6b0/ddtrace/tracer/spancontext.go#L23-L39) implementation would just reach back into `span` to get the values, which feels a little hacky.

Looking for ideas and feedback on how best to expose these.

**Comment by brettlangdon** [comment]
We will also want `Service()` as well to be available to inject into logs too

**Comment by gbbr** [comment]
Some ideas (without giving thorough thought):
* Alter the `String` method of `span` which is not public API and not really used so that it displays _all_ the needed information, giving us the possibility of doing things like:
```
log.Printf("Some message. Span: %s", span)
// Output: Some message. Span: dd.span_id: 123 dd_trace_id: 345 dd.env: prod ...
```
* Add a `SpanReader` method which takes a `Span` and returns an interface through which we can access various fields.

Frankly if this is simply for logging purposes, the first option (`fmt.Stringer`) seems natural and friendly to use. This is only good if we plan to standardise and set in stone the format of the output, which I think we are.
