### ISSUE TITLE
build: refactor circle build pipeline

### ISSUE THREAD

**Issue by roopakv** [DataDog/dd-trace-go#655]
There are few things that make it sort of hard to contribute to this repo in general and some of these can be fixed if we made changes to the circle build systems

- since this repo is not in go.mod mode developing is sort of hard and requires setting up and cloning this repo in the right place, and there arent instructions or steps (probably will be easier when we move to go.mod mode)
- running circle locally when the whole thing runs in one gigantic container means many systems die of resources. I for one have issues even after changing docker systems
- circle doesnt run until one of the maintainers adds a label.

I propose that we change the build pipeline as follows
- smaller jobs each testing one unit so that running locally with circle command is easier
- also allows people who have forks to just one click set up and run these containers since the containers that check things like copyright and labels will be their own check.
- finally will probably reduce the number of build minutes used.

I am happy to make these changes if @gbbr, @knusbaum and other maintainers are ok with this approach.

**Comment by gbbr** [comment]
I agree with you. The milestone check was something that I did in a hasty manner. I would've preferred it to be a separate job too. This work is more than welcome as far as I'm concerned.

Before you start work though, let's clarify all the details here first, to make sure we're doing the right thing...

> smaller jobs each testing one unit so that running locally with circle command is easier

Can we list the jobs we would have?

**Comment by roopakv** [comment]
there are many ways we could go
one of the approaches
```
- lint & copyright (one job, where copy right is the last step)
- test ~5 parts (some grouping where we group say all databases together, one for elastic,kafka and another... and finally one that runs all tests which dont need any docker container)
```

the negative to this approach is that when adding a new contrib package, it would have to be manually added to one of the containers, but I overall think it is a small prices to pay for better testability especially locally.

Another approach we could take for the tests is literally auto shard into ~5 containers, but this would mean we would need to run docker containers for say memcache in all containers even though we test only on one.

**Comment by gbbr** [comment]
I think I'd be fine with this initial split:

* Job 1: Copyright, milestone and other metadata related stuff (if more comes up later)
* Job 2: Tracer code (`ddtrace`)
* Job 3: Integrations (`contrib`)

We should start basic and this will be enough as phase 1. I think sharding and other things would be a bit overkill at this point. Our build is already fairly complicated and I'd like to avoid adding even more complexity into it. But I'm open to be convinced otherwise.

As for testing locally, I never use the `circleci` CLI so I can not fully relate to the problem you describe. I manually test whatever package I work on using `go test` and leave everything else up to CI.

**Comment by roopakv** [comment]
the negative of this is that the contrib job would still be an XL machine with many docker containers. As we add more libraries we support, this number will only increase. 

That said I think this can be a good start

**Comment by knusbaum** [comment]
Thank you for your contributions, @roopakv 

Getting the circleci cli working better would be a really good thing. I think giving contributors a standard way to test the entirety of `dd-trace-go` that works well will make contribution easier.

I tried the circleci cli briefly and gave up fairly quickly, preferring to use `go test` on whichever package I change. Since we suggest circleci cli in the README.md, we should support it.

Splitting into the three jobs @gbbr suggested should help, and we can look at breaking them down farther if job 3 is still too big.

**Comment by roopakv** [comment]
@knusbaum i'll send you a PR later when i get some time

**Comment by knusbaum** [comment]
@roopakv 
A lot has changed in the CI pipeline since this issue was filed and there are a bunch more changes to make CI/test running easier in the near future. I'm going to close this now, but feel free to reopen it or open a new issue about CI/testing troubles.
