### ISSUE TITLE
proposal: allow span.Finish to return err

### ISSUE THREAD

**Issue by jippi** [DataDog/dd-trace-go#661]
Over at @seatgeek we keep doing this pattern today

```go
func derp(ctx context.Context) error {
    span, ctx := tracer.StartSpanFromContext(ctx, "derp")
    defer span.Finish()

    if err := doSomething(ctx); err != nil {
        span.Finish(tracer.WithError(err))
        return err
    }

    return nil
}
```

would be nice to trim down to

```go
func derp(ctx context.Context) error {
    span, ctx := tracer.StartSpanFromContext(ctx, "derp")
    defer span.Finish()

    if err := doSomething(ctx); err != nil {
        return span.Finish(tracer.WithError(err))
    }

    return nil
}
```

or even

```go
func derp(ctx context.Context) error {
    span, ctx := tracer.StartSpanFromContext(ctx, "derp")
    defer span.Finish()

    err := doSomething(ctx); 
    return span.Finish(tracer.WithError(err))
}
```

and have `span.Finish()`  return `nil` if no `tracer.WithError()` was called (or if the err was empty in said call) - its a pretty frequent repetitive pattern we do to finish the span and return an err in individual lines

The last example can even be shortened down to in a theoretical case

```go
func derp(ctx context.Context) error {
    span, ctx := tracer.StartSpanFromContext(ctx, "derp")
    return span.Finish(tracer.WithError(doSomething(ctx)))
}
```

In technical terms, I would change the Span interface to 

```go
type Span interface {
	Finish(opts ...FinishOption) error
}
```

or expand it to include

```go
type Span interface {
	FinishWithError(err error, opts ...FinishOption) error
}
```

which could be as simple as

```go
func (s Span) FinishWithError(err error, opts ...FinishOption) error {
    span.Finish(tracer.WithError(err), opts...)
    return err
}

**Comment by gbbr** [comment]
I see. Personally I feel that if `Finish` were to return an error, it would have to be indicative of its outcome, whereas in this case it'd be there only superficially to simplify a very specific scenario. Not only that, but the return value would be dependent on an optional argument and would otherwise mean nothing. I don't think that's the way to go.

As for having an extra method, we've already rejected that proposal in the past (https://github.com/DataDog/dd-trace-go/issues/352) but I'll leave it here in case someone wants to chip and change it. It's worth noting that we've went a long way simplifying this API because previously there were just way too many things to do this.

What I'd recommend instead is a tracing helper module, similar to the below:

```
func FinishWithErr(span ddtrace.Span, err error) error {
    span.Finish(tracer.WithError(err))
    return err
}
```

To remove the apparent duplication.

**Comment by gbbr** [comment]
I would also like to advise that it's best to have only one `Finish` call per span, otherwise programming errors can occur and tracing might become inconsistent. For this reason, we sometimes do:
```
func something() (err error) {
    span, ctx := ...
    defer func() {
        span.Finish(tracer.WithError(err))
    }()
    // ...
}
```
It's not the nicest approach, and possibly wouldn't be a great idea in an exported function or public API, but it can make things a lot simpler in a function with many return paths.

**Comment by pwmcintyre** [comment]
i've been doing this, but i hate it....
```golang
func something(ctx context.Context) (err error) {
	span, ctx := tracer.StartSpanFromContext(ctx, "thing.doer")
	defer func() {
		if err != nil {
			span.Finish(tracer.WithError(err))
			return
		}
		span.Finish()
	}()
	...
}
```


but i would rather just always include error, and `Finish()` would just know what to do with it
```golang
func something(ctx context.Context) (err error) {
	span, ctx := tracer.StartSpanFromContext(ctx, "thing.doer")
	defer span.Finish(err)
	...
}
```

**Comment by knusbaum** [comment]
@pwmcintyre Thankfully you don't need to do the first thing, even today. Instead, you can do:
```go
func something(ctx context.Context) (err error) {
	span, ctx := tracer.StartSpanFromContext(ctx, "thing.doer")
	defer func() { span.Finish(tracer.WithError(err)) }()
	...
}
```
`tracer.WithError` will have no effect if `err` is nil, so you don't need to check it. `tracer.WithError` already knows what to do with it, as you said you would prefer.
It's still not as nice as it could maybe be since it requires an anonymous function wrapper, but I think it's nicer than what you are doing currently.

At first glance I like the other `Trace` function you proposed:
```go
tracer.Trace(ctx, "thing.doer", func(ctx context.Context) error{
	...
})
```
It reminds me of how subtests work in the `testing` package.

One concern I have about it is that I think users usually trace whole functions (this is why we see the `defer span.Finish()` pattern) and I'm not sure I like having to have every function start with `tracer.Trace(ctx, "thing.doer", func(ctx context.Context) error{` and having all the code indented into it. It's almost like a second function header and feels intrusive. Then again, it's not too much different from the start/defer pattern we have today, and anyone who doesn't like it could keep using the old method.

Feel free to open a proposal issue describing how it would work and what issues/annoyances it solves.

**Comment by pwmcintyre** [comment]
@knusbaum thanks for the tip

question, surely you don't need the anonymous function, since it's just one line - eg:
```
func something(ctx context.Context) (err error) {
	span, ctx := tracer.StartSpanFromContext(ctx, "thing.doer")
	defer span.Finish(tracer.WithError(err))
	...
}
```

this is nice, i like it 👌 

[opinion] this should be promoted in the docs!

**Comment by knusbaum** [comment]
@pwmcintyre Unfortunately, the anonymous function is still required even though it's only one line.
It is because Go evaluates the arguments to deferred functions when it encounters the `defer`, not when it actually calls the deferred function.

Here, `tracer.WithError(err)` is evaluated right away when we encounter the `defer`. If err is set *after*, in the `...` section, it won't be picked up.
```
func something(ctx context.Context) (err error) {
	span, ctx := tracer.StartSpanFromContext(ctx, "thing.doer")
	defer span.Finish(tracer.WithError(err))
	...
}
```

To work around this, we wrap the whole call in an anonymous function. There are now no arguments to the deferred function, meaning `tracer.WithError(err)` will be evaluated when the deferred function is *called* rather than when the `defer` is initially set up.
```
func something(ctx context.Context) (err error) {
	span, ctx := tracer.StartSpanFromContext(ctx, "thing.doer")
	defer func() { span.Finish(tracer.WithError(err)) }()
	...
}
```

**Comment by pwmcintyre** [comment]
@knusbaum appreciate the response, I recently found this out the hard way when my spans were failing to report errors 😅

Raised some discussion here
https://www.reddit.com/r/golang/comments/k1s78r/defer_versus_defer_func

**Comment by knusbaum** [comment]
Closing after rejection.
