### ISSUE TITLE
contrib/net/http: add support for customizing a resource name in RoundTrip

### ISSUE THREAD

**Issue by ichizero** [DataDog/dd-trace-go#689]
`* roundTripper.RoundTrip` sets the fixed value `http.request` in a resource name tag, so it is not possible to analyze each endpoint on the APM service page.

https://github.com/DataDog/dd-trace-go/blob/5ec4cda2230dc7ffe5e833f47957234c4ba7d50c/contrib/net/http/roundtripper.go#L27-L33

Therefore, I propose that `*roundTripper.RoundTrip` supports ResourceNamer like contrib/gin-gonic/gin or contrib/gorilla/mux.

https://github.com/DataDog/dd-trace-go/blob/5ec4cda2230dc7ffe5e833f47957234c4ba7d50c/contrib/gin-gonic/gin/option.go#L54-L74

**Comment by gbbr** [comment]
The default behaviour is as such because we don't want any potentially sensitive information in URLs to get away (auth tokens, etc). In other routers (like `gorilla/mux` and `gin`) we can use the route pattern which obscures all of that, but I guess this isn't possible in `net/http`.

I think it should be fine to add this feature and give more control to users. If you wish to open a PR, feel free to!

**Comment by ichizero** [comment]
Thank you for your reply!

I understand why the default behavior is this way. With that in mind, I'll open a PR.
