### ISSUE TITLE
gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http not setting span as error on HTTP 500

### ISSUE THREAD

**Issue by marciorodrigues87** [DataDog/dd-trace-go#728]
Hi guys! Looks like the http client tracer isn't setting the span as error when there's a 500 status code response

<img width="467" alt="Screen Shot 2020-09-09 at 11 20 13" src="https://user-images.githubusercontent.com/4513509/92610962-ad00a580-f28e-11ea-9eb6-3255f0730a9c.png">

Maybe add something here: https://github.com/DataDog/dd-trace-go/blob/v1/contrib/net/http/roundtripper.go#L62 to mark that the span wasn't OK could solve the problem (if it's really a problem 😄 )

My code to wrap the http client:

```go
var (
	httpTimeout             = common.Config.GetInt("httpTimeoutSeconds")
)

var httpTimeoutDuration = time.Duration(httpTimeout) * time.Second

var customHTTPTransport = &http.Transport{
	Proxy:                 http.ProxyFromEnvironment,
	DialContext:           timeoutDialer(httpTimeoutDuration, httpTimeoutDuration),
	MaxIdleConns:          common.Config.GetInt("httpMinConnections") * 10,
	MaxIdleConnsPerHost:   common.Config.GetInt("httpMaxConnections"),
	IdleConnTimeout:       httpTimeoutDuration,
	TLSHandshakeTimeout:   httpTimeoutDuration,
	TLSClientConfig:       &tls.Config{InsecureSkipVerify: true},
	ExpectContinueTimeout: httpTimeoutDuration,
}

....

func setupHTTP() {
	HTTP = &http.Client{
		Transport: customHTTPTransport,
		Timeout:   httpTimeoutDuration,
	}
	HTTP = httptrace.WrapClient(
		HTTP,
		httptrace.RTWithServiceName("http-client"),
		httptrace.RTWithResourceNamer(func(req *http.Request) string {
			return req.URL.String()
		}),
	)
}

```

**Comment by marciorodrigues87** [comment]
Here's a workaround:

```go
	HTTP = httptrace.WrapClient(
		HTTP,
		httptrace.RTWithServiceName("http-client"),
		httptrace.RTWithResourceNamer(func(req *http.Request) string {
			return req.URL.String()
		}),
		httptrace.WithAfter(func(res *http.Response, span ddtrace.Span) {
			if res != nil && res.StatusCode/100 == 5 {
				span.Finish(tracer.WithError(fmt.Errorf("http status error %d", res.StatusCode)))
			}
		}),
	)
```

**Comment by knusbaum** [comment]
This seems like a good idea. We do the same thing in the `gin-gonic/gin` integration (#449)

It should be as simple as setting the `ext.Errors` tag [exactly where you suggested](https://github.com/DataDog/dd-trace-go/blob/e7d03f2c9f20f6b31de1ae1635192e4f3109702e/contrib/net/http/roundtripper.go#L62) like we do [in the `gin-gonic/gin` integration](https://github.com/DataDog/dd-trace-go/blob/e7d03f2c9f20f6b31de1ae1635192e4f3109702e/contrib/gin-gonic/gin/gintrace.go#L56)

We probably want to do it right above, [here](https://github.com/DataDog/dd-trace-go/blob/e7d03f2c9f20f6b31de1ae1635192e4f3109702e/contrib/net/http/roundtripper.go#L57) too while we're at it.

@marciorodrigues87 feel free to put up a patch. Otherwise, I'll get around to it in the next couple days.

**Comment by marciorodrigues87** [comment]
Nice! Thank you for the tips @knusbaum! Here's the PR:

https://github.com/DataDog/dd-trace-go/pull/736
