### ISSUE TITLE
contrib/go-redis: key not being found always generates error

### ISSUE THREAD

**Issue by BaneOfSerenity** [DataDog/dd-trace-go#74]
I setup tracing for redis-go and data flows through from a redis call and sends a trace off to datadog fine. I noticed that when i call redis (ex: GET "key") if the value doesn't exist datadog picks it up as an error and logs in a stack trace. A key not being found in redis is a valid use case in our application and show not generate an error. http://prntscr.com/ff6it6 <- screenshot of what it looks like in datadog. The error is "internal.RedisError: redis: nil", note the "redis: nil" just means that there was no value to find from the key.

**Comment by furmmon** [comment]
Hey @BaneOfSerenity,  `go-redis` library returns an error whenever you do that action (Get non_existent_key). Redis doesn't but we catch what the connector gives you as an error. In the future we should provide a tool to filter errors in function of their type, so that you could set for that case that you do not consider it as an error

**Comment by gbbr** [comment]
@BaneOfSerenity sorry for the late reply - do you have any updates on this? Is this still an issue for you? I'm trying to groom the issues on the project and see what's still valid and what isn't. Would appreciate some input.

**Comment by niamster** [comment]
It would be nice to have a possibility to define a function to filter the errors.

**Comment by gbbr** [comment]
Fixed in #234.
