### ISSUE TITLE
proposal: option for ignore sampling on error

### ISSUE THREAD

**Issue by isbang** [DataDog/dd-trace-go#763]
It would be great if there is an option for ignore sampling on error.

#### Example
```go
func foo() {
	tracer.Start(
		tracer.WithAnalyticsRate(0.1),
		tracer.WithoutSamplingOnError(),
	)
	// or
	span := tracer.StartSpan("operation",
		tracer.WithoutSamplingOnError(),
	)
}
```

#### Result
```go
func bar() {
	span := tracer.StartSpan("operation")
	span.Finish(
		tracer.WithError(errors.New("This error ignore sampling")),
	) // this span will never be sampled
}
```

**Comment by gbbr** [comment]
Errors are very relevant to most users, why do you want this functionality? To ignore some trace resources, it's also possible to use `apm_config.ignore_resources` in the agent ([link](https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml#L770))

**Comment by isbang** [comment]
I think the meaning was misrepresented. I thought "sampled" means "filtered (not captured)". (my mistake. sorry)

In my case, I use datadog apm to trace error sometime. And almost of the case, the span with error was not captured because of 0.1 analytics rate and could not be traced. Then I thought if there is an option to ignore analytics rate, it would be useful. It is just a simple, creative idea. :)

**Comment by gbbr** [comment]
The trace should be captured regardless, especially for errors. The analytics rate only defines what ends up in App Analytics, it doesn't mean that the trace won't be accessible in Datadog.

If there are certain select spans that you would definitely want to keep, you can simply add a priority onto them:
```
span.SetTag(ext.ManualKeep, true)
```
This will guarantee that the span ends up in Datadog. Do note though that using this everywhere will definitely increase billing, so use it wisely only where you must.

Regularly this shouldn't be needed because there is special logic in the Datadog Agent which ensures errors are caught. If you think there is a problem there, I recommend reaching out through support because they'll be more than happy to guide you with all aspects of the product.

**Comment by isbang** [comment]
Wow, thanks for your help. I didn't know there was such an option. And I'll reach out through support after I review once more to see if there is a problem with the DataDog agent.

It's ok to close Issue. Thank you again.

**Comment by gbbr** [comment]
You're welcome! Anytime!
