### ISSUE TITLE
ddtrace/tracer childOf fails if parent span does not contain sampling tags

### ISSUE THREAD

**Issue by Jesse-Cameron** [DataDog/dd-trace-go#793]
👋  Just wanting to confirm if this is the expected behaviour or not.

I am implementing distributed tracing in datadog via an SQS queue. The trace flow is basically `ScalaApp -> SQS -> GolangApp`. I am using the TextMap injector to add the span context into a [message attribute](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html). The [scala library](https://github.com/zalando-incubator/opentracing-sqs-java) that I am using to add the span context doesn't inject a sampling rate. Which causes the golang trace client to be unable to construct a span from the parent span context

Here is my sample code:

```golang
mstStr := msg.MessageAttributes["span_ctx"]
res := make(map[string]string)
_ = json.Unmarshal([]byte(mstStr), &res)

sctx, _ := tracer.Extract(tracer.TextMapCarrier(res))

jobSpan := tracer.StartSpan("job.dispatch", tracer.ChildOf(sctx)) // this won't work
jobSpan := tracer.StartSpan("job.dispatch", tracer.ChildOf(sctx), tracer.Tag("_sampling_priority_rate_v1", float32(1)), tracer.Tag("_sampling_priority_v1", float32(1))) // this will work
```

As you can see. Once I add the `_sampling_priority_rate_v1` and `_sampling_priority_v1` tags manually. The trace appears in SQS correctly.

Thanks for having a look into this.

**Comment by Jesse-Cameron** [comment]
Hi again 👋 

I did a little bit of poking around and I have an idea for a fix. We could set a default sampling rate in the [`tracer.StartSpan`](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/tracer.go#L237) call.

```golang
if context != nil {
	// this is a child span
	span.TraceID = context.traceID
	span.ParentID = context.spanID
	if p, ok := context.samplingPriority(); ok {
		span.setMetric(keySamplingPriority, float64(p))
	} else {
		span.setMetric(keySamplingPriority, float64(1))
	}
        // snip
}
```

Let me know if this works on your end. I'm sure that there is some larger context that I am missing around how you implement sampling rates in your agents/etc.

Happy to put together a PR.

**Comment by knusbaum** [comment]
Hi, @Jesse-Cameron 

This solution could work, but I'd like to clarify what issues you see when constructing a span without a priority set. That will affect the kind of solution we want.

**Comment by Jesse-Cameron** [comment]
Hey @knusbaum ,

Sure, let me provide more details.

In my application, when I _don't_ have the priority set the span (`job.dispatch`) never shows up in our datadog dashboard. Not even as a span without a parent. As soon as I do set the priority the span appears in the parent trace. Also, if I construct a span that doesn't inherit from a parent, or inherits from a parent that was created with a priority. It works fine without the tag.

I couldn't see any error logs from our datadog agent. But admittedly, I didn't really know what I was looking for. 

Does that help?

**Comment by knusbaum** [comment]
Thanks, @Jesse-Cameron. That helps clarify things.

This is my understanding:
When we start a new trace, we apply the sampling logic and a priority is set:
https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/tracer.go#L321-L325

When we start a new span that is a child, this sampling logic doesn't get applied, and we expect there to be a priority in the parent context:
https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/tracer.go#L271-L275

If there is no priority in the parent context, we never set any priority.

We can solve this in 2 ways:
1. As you suggested, apply a sampling priority of auto keep - This will work, but might result in an over-prioritization of these spans.
2. Apply the sampling logic when no priority is available (basically `t.sample(span)` in an `else` block [here](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/tracer.go#L275)) - This should help make sure these spans have a priority without making them all auto keep. However, it could still result in some missing spans in a full trace.

I would prefer number 2, since I think it's more consistent with how the rest of the product works. Would you be able to test if this solution works for your case? If not, we can consider option 1.

**Comment by Jesse-Cameron** [comment]
Hey @knusbaum , 

I just did a quick test of option 2 and it solved the issue I was was seeing.

If you are happy with option 2, I can move forward with putting up a PR using that approach?

**Comment by knusbaum** [comment]
@Jesse-Cameron That would be fantastic. The plan looks good to me.
