### ISSUE TITLE
Multiple tracers into single Span

### ISSUE THREAD

**Issue by Jurabek** [DataDog/dd-trace-go#828]
I am struggling with `Datadog Tracing in Golang`, here is the problem description:
sample code here:

```
import (
	muxtrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/gorilla/mux"
	awstrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/aws/aws-sdk-go/aws"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)
func main() {
	tracer.Start(tracer.WithDebugMode(true))
	defer tracer.Stop()
	// db setup
	dynamoDb := dynamodb.New(awstrace.WrapSession(sess))
	// router setup
	r := muxtrace.NewRouter(muxtrace.WithServiceName("test" + ".router"))
	r.HandleFunc("/getItems", func(w http.ResponseWriter, r *http.Request) {
	      items := dynamoDb.scanItem(parmas)
	      ....
	      w.WriteHeader(http.StatusOK)
	}).Methods("GET")
	err := http.ListenAndServe(":5000", r)
}
```
### expected tracing:
```
Mux Router /getItems() > Dynamodb scanItem()
         |                       |
    Parent                    Child
```

when I look at traces collection, Router and DynamoDb are not connected to each other they are not under the single span, is there any way to connect multiple tracers into a single span context? 

the attached screenshot shows two traces which is not connected to each other
<img width="1462" alt="Screenshot 2020-11-06 at 15 37 02" src="https://user-images.githubusercontent.com/8397056/106206573-99fc5c80-61c0-11eb-8027-82a75bd9a182.png">

We would appreciate any examples or suggestions.

**Comment by Jurabek** [comment]
I created an example repository with Docker Compose 
https://github.com/Jurabek/golang-datadog-multi-tracer

**Comment by knusbaum** [comment]
Hi, @Jurabek. Thanks for the question.

Whenever you want to connect two services into a single trace, you should make sure you are passing the correct `context.Context` object around.

The Go tracer plumbs its live spans through different parts of an application through contexts, and so in order to create child spans of an existing trace, we need to have the right context to pull the current span from.

[Here](https://github.com/Jurabek/golang-datadog-multi-tracer/blob/d61e02e94fcb4cfa04f2559051dcc2e627cb3c36/main.go#L38), for instance, rather than using `Scan`, try [`ScanWithContext`](https://pkg.go.dev/github.com/aws/aws-sdk-go/service/dynamodb#DynamoDB.ScanWithContext).

The context you need will be inside the http request object and can be retrieved with [`r.Context()`](https://pkg.go.dev/net/http#Request.Context)

Please let me know if this resolves you issue.

**Comment by Jurabek** [comment]
@knusbaum Thank you very much for your answer, it solved my problem.
