### ISSUE TITLE
Continuing a distributed trace with this library is extraordinarily unclear

### ISSUE THREAD

**Issue by SophisticaSean** [DataDog/dd-trace-go#914]
It took me about a day of ripping through this library to understand how to manually continue a trace given a parent span id and a trace id.

This is what I ended up with which feels needlessly esoteric (and is absolutely poorly documented at best): 

```go
	traceID := req.GetTraceId()
	strTraceID := strconv.FormatUint(traceID, 10)
	parentSpanID := req.GetParentSpanId()
	strParentSpanID := strconv.FormatUint(parentSpanID, 10)

	// configure contextual logger
	subLogger := log.With().
		Str("trace_id", strTraceID).
		Str("parent_span_id", strParentSpanID).
		Str("asset", req.GetAsset().String()).
		Logger()

	// try to propagate trace and parent id from the request
	ddHeaders := tracer.TextMapCarrier{
		"x-datadog-trace-id":  strTraceID,
		"x-datadog-parent-id": strParentSpanID,
	}

	extractedCtx, err := tracer.Extract(ddHeaders)
	if err != nil {
		subLogger.Error().Err(err).Msg("could not extract ddHeaders")
		panic(err)
	}

	span := tracer.StartSpan("grpc-serve", tracer.ChildOf(extractedCtx))
	defer span.Finish()


```

**Comment by SophisticaSean** [comment]
I'm happy to make the change to fix it, I just want advice on what y'all recommend? I personally think we should add a `tracer.ContinueTrace(trace_id, parent_span_id) (spanCTX, error)` method.

**Comment by felixge** [comment]
Hey @SophisticaSean, sorry you had a frustrating experience with this! I work on the `profiler` package, so I'll leave it to @gbbr or @knusbaum to take a look.

Anyway, the code snippet you're showing looks indeed very cumbersome. If there is a better way, we need to make it more obvious. If not I'd be supportive of considering a new API. Thank you so much for offering your help on that!

**Comment by SophisticaSean** [comment]
Thanks a ton for responding! :) yeah I couldn't find a cleaner way to do it so if someone knows let me know!

**Comment by knusbaum** [comment]
Hi, @SophisticaSean. Sorry for the late response.

You have it right. Using the `Extract` and `ChildOf` functions to manually create a child of a distributed trace is the way to go. I would recommend using the header constants defined in the `tracer` package rather than string literals though:
https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.31.0/ddtrace/tracer#pkg-constants

When propagating a distributed trace, we usually include a Priority as well to make sure whole traces are appearing/being dropped. 

Propagating distributed traces can be a little tricky, and we are liable to add additional information, so we usually try to take care of that through the integrations (e.g. through HTTP headers, grpc metadata, etc.). I'm interested to know your use case and to see if we can cover it in a better way so that you don't have to manually propagate them.

If not, we can talk about what an appropriate API might be for making continuing a trace easier, like your `ContinueTrace`.

**Comment by knusbaum** [comment]
I am going to close this now for being stale.

Please reopen or start a new issue if you would like to propose a new API or syntax for distributed tracing.
