### ISSUE TITLE
Passing nil value of *time.Time into span.SetTag results in panic

### ISSUE THREAD

**Issue by ptsurko** [DataDog/dd-trace-go#928]
Passing nil value of *time.Time into span.SetTag results in panic. 

Code example:
```
var timeAt *time.Time
...
span, ctx := tracer.StartSpanFromContext(ctx, "name")
span.SetTag("startAt", timeAt) // timeAt is nil
```

Crashes with error: `value method time.Time.String called using nil *Time pointer`

I think this is because String is declared on time.Time and not on pointer.

This is related to this commit: https://github.com/DataDog/dd-trace-go/commit/75d7e5311c7df567073593d6a0f197564f468d5e

**Comment by gbbr** [comment]
Thanks for reporting this. I guess a good solution would probably be adding something like this into `SetTag`:
```go
if value == nil {
    s.setMeta(key, "")
    return
}
```

**Comment by knusbaum** [comment]
On closer inspection, this is not nearly as simple as it seems. In fact, it shows something really surprising about Go in general.

## Investigation 

Go allows (and even encourages) calling pointer-receiver methods on `nil` objects. (https://tour.golang.org/methods/12). Go assumes that any method taking a pointer receiver should handle a `nil` receiver. This is [everywhere throughout the standard library](https://cs.opensource.google/go/go/+/refs/tags/go1.16.4:src/net/net.go;l=174). 

This is more than just convention, though. The language itself assumes this pattern. Surprisingly, detecting a `nil` interface value cannot be done without reflection. Interface values are not `== nil`, even if the underlying concrete value is `nil` (unless both the type and value of the interface are `nil`, but that's not relevant to our case). This means we can't simply check `if value == nil`. The check won't catch this case and won't fix the panic. 

Go seems to tell us that we can call `.String` on any object that satisfies (`fmt.Stringer`), since the methods themselves should handle `nil` receivers. However, the language itself seems to break this rule by allowing a `*time.Time` to say it implements `fmt.Stringer` even though it doesn't (`time.Time` does). This means a `nil` `*time.Time` will satisfy `fmt.Stringer`, but it is *not* safe to call `.String()` on it - it will cause a panic.

Figuring out which methods are safe to call and which are not is not simple, and in fact Go's `fmt` package, which runs into this issue, doesn't even try. [It just calls them and sees if a panic happens...](https://cs.opensource.google/go/go/+/refs/tags/go1.16.4:src/fmt/print.go;l=623-627;drc=c89f1224a544cde464fcb86e78ebb0cc97eedba2)

While not authoritative, [this message](https://groups.google.com/g/golang-nuts/c/wnH302gBa4I/m/i_cPI8Gu9P8J) seems to summarize the position of Go on this topic: 
> This is a common source of confusion.  **The basic answer is to never store something in an interface if you don't expect the methods to be called on it.**  The language may allow it, but that violates the semantics of the interface.  To expound, a nil value should usually not be stored in an interface unless it is of a type that has explicitly handled that case in its pointer-valued methods and has no value-receiver methods.

However, this does us no good. The caller can't know that we will cast to `fmt.Stringer`, and so can't know not to pass any pointers to objects with value-receiver `.String` methods. Even if we documented it, we would never want an API that won't accept objects with certain properties which the caller is not likely to know. (Does type `x` implement `fmt.Stringer` with a value-receiver?). Likewise, it looks like we can't easily check if the caller passed us such a value-receiver `fmt.Stringer`.

[Ian Lance Taylor](https://research.google/people/author37504/) had [this to say](https://groups.google.com/g/golang-nuts/c/wnH302gBa4I/m/QTwtmj16AgAJ):
> The issue of passing a nil pointer to a value method is a good reason to write your String methods as pointer methods.

Again, this does us no good, and is especially surprising since types that are part of the go standard library (such as `time.Time`) have `String` methods with value-receivers.

This basically leaves us in a position where it's not safe to call `.String()` (or really any interface method) on an object passed by a user, for which we've done an interface type check. Reverting the `fmt.Stringer` check, and the call to `.String()` may be our best option. Otherwise we will likely need to do what the `fmt` package did and catch and handle panics when a `fmt.Stringer` panics.

## Other People Running Into the Same Wall

https://groups.google.com/g/golang-nuts/c/wnH302gBa4I/m/QvXhxORwAgAJ
https://groups.google.com/g/golang-nuts/c/wnH302gBa4I/m/385ehaY0BAAJ

## Summary / TL;DR

1. Certain objects say they implement `fmt.Stringer`, but panic when '.String()` is called. (This is true for any interface/method)
2. This situation is not easy to detect. Detecting `nil` is possible with reflection, but does not handle the situation correctly, since passing `nil` to `.String()` with a pointer receiver is valid and expected.
3. Our options seem to be to revert the optimization (#799) or to implement a panic handler.
