### ISSUE TITLE
Version 1.31.0 is missing in tags

### ISSUE THREAD

**Issue by mfechner** [DataDog/dd-trace-go#929]
Dear all,

FreeBSD depends for go modules on tags hosted on github.
It seems that the go modules was released here:
https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.31.0

But not on github.

To be able to build packages using version 1.31.0 FreeBSD (freebsd.org) requires the package to be existing on github.

Is it possible to add the missing tag?

Thanks a lot.

**Comment by felixge** [comment]
cc @knusbaum @gbbr I can add the tag, should I? Or was 1.31.0 release to pkg.go.dev by accident?

**Comment by wouafff** [comment]
+1

**Comment by gbbr** [comment]
We will be releasing `v1.31.0` next, and then it should be fine. Not exactly sure how this happened...

**Comment by dmitshur** [comment]
> Not exactly sure how this happened...

What I wrote in https://github.com/golang/go/issues/46348#issuecomment-847189748 may be relevant.

Perhaps PR #910 and issue #911 are also relevant, since there are mentions of `v1.31.0` in them, and their dates are close after the index date.

> We will be releasing `v1.31.0` next, and then it should be fine. Not exactly sure how this happened...

Please be mindful that if v1.31.0 was published previously and its tag was deleted, there may be checksum entries for that version in some user's go.sum files and in the checksum database (https://sum.golang.org/), so if v1.31.0 is published with a different content, it will have a non-matching checkum. (If it's pushed with the same content, the checksum should match.)

[Module retraction](https://blog.golang.org/go116-module-changes#TOC_5.) may be relevant here.

**Comment by gbbr** [comment]
Thanks for jumping in here @dmitshur. I'd suggest that probably the best solution here would be to go for `v1.31.1` as a "patch" for the bad tag incident.

**Comment by knusbaum** [comment]
Version `v1.31.1` has just been published, so this should be fixed. Version `v1.31.0` is still not available, but any future `go get gopkg.in/DataDog/dd-trace-go.v1` should get the later version, not the bad `v1.31.0` version.

Sorry for the inconvenience.
